### ISSUE TITLE
Support for all display types

### ISSUE THREAD

**Issue by 2dom** [2dom/PxMatrix#1]
Continued discussion from https://github.com/2dom/P10_matrix/issues/7

**Comment by irazaq** [comment]
tested it with the ESP.wdtFeed() and the "Pixel Time" display hung for about 29secs before it crashed.
After some playing around, I decide to increase the value of the ticker period from 0.001 to 0.002 as I assume it was a timer issue. The problem disappear and now it is working with show_time of 70 without the watchdog feed.

**Comment by 2dom** [comment]
Great ... no flicker with the new period ?

**Comment by irazaq** [comment]
not noticeable.
I changed the delay period in the loop to 10, 500, 1000ms. 
[P5-files.zip](https://github.com/2dom/PxMatrix/files/1865178/P5-files.zip)

**Comment by 2dom** [comment]
ok ... looking good - great! Will push this change to master.
