### ISSUE TITLE
New chipset on the market?

### ISSUE THREAD

**Issue by chhofi** [2dom/PxMatrix#104]
Hello,

the last days I try to get my 64x32 panel to work. Unfortunately without great success. When looking closer at the board I realized, that it is not using any of the known chips. The are different chips on the board: DP5020B, RUC7258 and 74HC245C.
The supplier said it is using a normal HUB75 interface. Also Pin E is grounded. So probably not used.

Should the library work with those chips too? 
Has anyone got any experience with that specific LED board?

Link to the board on Aliexpress:
https://www.aliexpress.com/item/32902068286.html?spm=a2g0s.9042311.0.0.5cd94c4dzOgXcG

Cheers,
Christian

![LPvf++QJTs+WO%4dj74AdQ_thumb_2143](https://user-images.githubusercontent.com/38223379/58763246-bc0b8a80-8558-11e9-8ecf-d5545fbc0160.jpg)
![nMJHD6RERrmwx+qFoAmdQQ_thumb_2140](https://user-images.githubusercontent.com/38223379/58763249-bc0b8a80-8558-11e9-918c-5b1d23769bb2.jpg)
![qC8NAqWLScatQkIJEtEEbg_thumb_214a](https://user-images.githubusercontent.com/38223379/58763250-bc0b8a80-8558-11e9-96ac-7bf3c93be554.jpg)
![UNADJUSTEDNONRAW_thumb_2141](https://user-images.githubusercontent.com/38223379/58763251-bc0b8a80-8558-11e9-8468-132ec047a227.jpg)

**Comment by chhofi** [comment]
Here a picture of the "Pixel Time"
![02B23701-BF00-46ED-B92D-1DAAA776F5CA](https://user-images.githubusercontent.com/38223379/58763264-f117dd00-8558-11e9-8c1f-1467fd758ff9.jpg)
 test

**Comment by 2dom** [comment]
Could you run the pattern test and post the result?

**Comment by chhofi** [comment]
Sure. I also ran the "Pixel Time" sketch again.

https://youtu.be/tBEZxhWevRs
https://youtu.be/eb2GSpwCbzU

In real it looks the same as in the videos.

**Comment by 2dom** [comment]
Strange ... Read the data sheets...seems ok. Anyone else having this panel?

**Comment by HoLo85** [comment]
Hi, not the same panel, but a 64x64 with the same chipset and the same problem.
The E line on my panel is used and if i disconnect the E line the missing part of the text is sometimes visible but constantly flickering, so maybe its a timing issue?

I can use the panel with hzellers library for the raspberry, but sadly not with the esp8266 or esp32.

**Comment by serestre** [comment]
i have same problem
![WhatsApp Image 2019-08-30 at 09 17 03](https://user-images.githubusercontent.com/11726268/64042144-d8529f80-cb26-11e9-8bc6-ad76d56c586a.jpeg)

**Comment by 2dom** [comment]
This is solved in the latest master ... the multiplxer chips on some panels are too slow. You can now configure the mux delay as follows:

```
  display.begin();
  display.setMuxDelay(0,1,0,0,0);
```

This would add some delay to the B channel.

**Comment by 2dom** [comment]
Just experiment a bit, e.g. start with 1us on all channels an then reduce until problems occur

**Comment by Porokoura** [comment]
> 
> 
> Hello,
> 
> the last days I try to get my 64x32 panel to work. Unfortunately without great success. When looking closer at the board I realized, that it is not using any of the known chips. The are different chips on the board: DP5020B, RUC7258 and 74HC245C.
> The supplier said it is using a normal HUB75 interface. Also Pin E is grounded. So probably not used.
> 
> Should the library work with those chips too?
> Has anyone got any experience with that specific LED board?
> 
> Link to the board on Aliexpress:
> https://www.aliexpress.com/item/32902068286.html?spm=a2g0s.9042311.0.0.5cd94c4dzOgXcG
>
> Cheers,
> Christian
> 
> ![LPvf++QJTs+WO%4dj74AdQ_thumb_2143](https://user-images.githubusercontent.com/38223379/58763246-bc0b8a80-8558-11e9-8ecf-d5545fbc0160.jpg)
> ![nMJHD6RERrmwx+qFoAmdQQ_thumb_2140](https://user-images.githubusercontent.com/38223379/58763249-bc0b8a80-8558-11e9-918c-5b1d23769bb2.jpg)
> ![qC8NAqWLScatQkIJEtEEbg_thumb_214a](https://user-images.githubusercontent.com/38223379/58763250-bc0b8a80-8558-11e9-96ac-7bf3c93be554.jpg)
> ![UNADJUSTEDNONRAW_thumb_2141](https://user-images.githubusercontent.com/38223379/58763251-bc0b8a80-8558-11e9-8468-132ec047a227.jpg)

Hello! Have you solved the problem?

**Comment by chhofi** [comment]
Now I had some time for testing. It is working great! Thanks a lot for the new feature!!!

**Comment by Porokoura** [comment]
Did you add mux delay to each channel or just to one individual?
What else did you do?

**Comment by Porokoura** [comment]
> 
> 
> Now I had some time for testing. It is working great! Thanks a lot for the new feature!!!

I would be interrested to hear what was your solution for a problem.

**Comment by chhofi** [comment]
-> Just experiment a bit, e.g. start with 1us on all channels an then reduce until problems occur
I tried some different values. But now I switched to the RaspberryPi, because for my project I needed more computing power.
