### ISSUE TITLE
P10 32x16 incorrect row display 

### ISSUE THREAD

**Issue by kaung29** [2dom/PxMatrix#108]
![IMG_20190615_140049](https://user-images.githubusercontent.com/51666405/59550477-16f9a480-8f91-11e9-8bf4-6fd0cc703001.jpg)
![IMG_20190615_140053_1](https://user-images.githubusercontent.com/51666405/59550508-71930080-8f91-11e9-9b3d-5088d78ad6c8.jpg)

my very first time led project. I use Nodemcu esp8266 board.
I attach the photo .. test with pattern_test

**Comment by 2dom** [comment]
Could you post a video of gif?

**Comment by AeroX2** [comment]
This P10 matrix looks very similar to mine and I think I'm having the same issue.
I've tried different scanning and muxing patterns but it always results in the same behaviour.

Here is a video of the effect: https://youtu.be/jZTgdUTgVeE

**Comment by AeroX2** [comment]
Had a look into this myself and managed to get my display working but I had to make changes to the PxMatrix.h. It took a while to troubleshoot and probably would have been nice to have known that displayTestPattern doesn't use the scanning patterns.

But in the end, I used the ZIGZAG pattern and swapped lines 563 and 565 in PxMatrix.h:
`total_offset_r=base_offset-row_sector__offset*row_sector-(_scan_pattern==ZAGGIZ ? 1: 0);` 
`total_offset_r=base_offset-row_sector__offset*row_sector-(_scan_pattern==ZIGZAG ? 1: 0);`

Not sure if there was a set of parameters that I missed that would do this but this worked for me.

**Comment by 2dom** [comment]
Well yes ... `display.setScanPattern(ZAGGIZ)` would do the same. The whole point of the pattern test is to  just shifts in bytes to reveal the internal structure of the matrix. The pattern test would, however, not show reversed byte patterns. You could then use displayTestPixel.
