### ISSUE TITLE
how to make 64x64 from p5 32x32 4 panels ?

### ISSUE THREAD

**Issue by theravenesia** [2dom/PxMatrix#109]
how to make 64x64 from p5 32x32 4 panels ?

**Comment by soulid** [comment]
Would be really interesting to me as well. I have the same issue with stacking 2 Panel each 64x32.
Is the pull request #51 potentially solving the issue?

See here: https://github.com/2dom/PxMatrix/pull/51

**Comment by 2dom** [comment]
Not out of the box. But you could  put 4 of them in a row. You then have to do some simple algebra to map everything beyond 32 vertical to the second set of panels
