### ISSUE TITLE
My matrix's word is reversed

### ISSUE THREAD

**Issue by hoangnamzero251** [2dom/PxMatrix#115]
Hi 2dom !
My matrix's word is reversed, such as "p" => "q" . if i print "an" , "a" will be reversed and between two part of "n" (reversed) . 
I use "Zigzag" scan pattern and setMuxPattern is Binary.
My matrix scan rate is 1/8.

**Comment by 2dom** [comment]
Ok ... pull the lates master ... I added a flip option. Try setting

`display.setFlip(true);`

after begin,

**Comment by 2dom** [comment]
Re-open if this does not do the trick.
