### ISSUE TITLE
False pixels

### ISSUE THREAD

**Issue by wavewolf** [2dom/PxMatrix#118]
I'm using an Adafruit 16x32 1/8 RGB matrix panel and I'm having unwanted behaviors.

When I command to write anything with the "print" function or any other function, there are several pixels on the screen unwanted and it looks very bad visually.

![error](https://user-images.githubusercontent.com/22566382/62243463-9cb89e80-b3dd-11e9-95ae-1f6fb4f9e599.jpg)

![photo_2019-07-31_22-02-52](https://user-images.githubusercontent.com/22566382/62244098-008f9700-b3df-11e9-90be-48d4ad29aaaf.jpg)

I don't know how to solve it, any idea?

**Comment by robjen** [comment]
this is not an error in the code library   it is electrical noise ... tidy up your wiring and make sure your ground connections are good !

**Comment by 2dom** [comment]
@robjen is probably right ... also make sure that your power supply is at least 3A and that you use cables that can handle the current. Please re-open if this does not help.
