### ISSUE TITLE
No data out with FM6126A

### ISSUE THREAD

**Issue by cQszasza** [2dom/PxMatrix#120]
Hi guys, 

I'm trying to use this lib with a nodemcu-32s and a 32x64 display with FM6126A chipset but if I add display.setDriverChip(FM6126A); to setup no data or clock is coming out from the ESP. ABCD, OE, and LATCH lines are doing their thing (confirmed with scope) But nothing on CLK and MOSI pins. If I comment out the setDriverChip line there is data coming but obviously the display isn't working. Any ideas?

**Comment by cQszasza** [comment]
I've tried it with [this fork](https://github.com/kkaoo/PxMatrix) and it is working now. Its just weird that the original library isn't.

**Comment by 556duckvader** [comment]
> 
> 
> I've tried it with [this fork](https://github.com/kkaoo/PxMatrix) and it is working now. Its just weird that the original library isn't.

I take it this fork is only for ESP32's

**Comment by 2dom** [comment]
Hi guys ... just merged the changes by @kkaoo ... do you want to give it another try?

**Comment by cQszasza** [comment]
Its working fine now with this lib, the brightness setting as well.  I'm using gpio 27 instead of gpio 2 for OE, I just couldn't upload with gpio 2 connected.

**Comment by 556duckvader** [comment]
> 
> 
> Its working fine now with this lib, the brightness setting as well. I'm using gpio 27 instead of gpio 2 for OE, I just couldn't upload with gpio 2 connected.

Can you post a pic of your wiring?  I am trying to make sure I have mine wired up correctly.
