### ISSUE TITLE
Arduino IDE does not update Library, version misconfiguration

### ISSUE THREAD

**Issue by hallard** [2dom/PxMatrix#123]
I spent some time to understand why Arduino IDE says latest version was 1.3.0 and not 1.3.5, this is because the file `library.properties` is not in sync with release avoiding Arduino IDE to upload latest version. The field version should be 1.3.5 and updated in sync to every release published on github
```
version=1.3.0
```
should be 
```
version=1.5.0
```
Anyway doing this now will not change anything because the 1.5.0 release contains file with version 1.3.0, so this will only be fixed on next release, may be 1.6.0, but change file `library.properties` need to be adjusted before publishing the release, so 
```
version=1.6.0
```

**Comment by 2dom** [comment]
Thanks ... i missed this. Will do it right next time
