### ISSUE TITLE
How to use latch or display after filling buffer

### ISSUE THREAD

**Issue by RobertHolscher** [2dom/PxMatrix#132]
Hi , I am looking to fill the buffers first with data but not showing on the matrix until a certain command. Like the latch on and off. However I have not managed to find an example of this.
Can you point me in the right direction ?
The info is in streams over the internet in my project and the delay it is noticable on the display. So i want to fill the buffers first with the data and when complete, show it on display in one go. There is no way I can keep the data in memory, so it needs to fill the buffers directly and when all is in, show

It is like the show function on many LCD arduino displays

**Comment by 2dom** [comment]
This is pretty much what double buffer does (see examples) ... the display itself has no memory
