### ISSUE TITLE
Need New Scan pattern

### ISSUE THREAD

**Issue by wardi1971** [2dom/PxMatrix#133]
Add need new scan patern for my led matrix Cai Liang 1/4 scan.

I add this code in PxMATRIX::fillMatrixBuffer in line number 447 

for (uint8_t yy = 0; yy<_height; yy+=2*_row_pattern)
    {
      if ((yy<=y) && (y<yy+_row_pattern))
        total_offset_r=base_offset-row_sector__offset*row_sector-(_scan_pattern==ZAGGIZ ? 1: 0);

//  ==== add new scan patter GAZGIZ =============== start
      if ((yy<=y) && (y<yy+_row_pattern))
        total_offset_r=base_offset-row_sector__offset*row_sector-(_scan_pattern==GAZGIZ ? 1: 0);
//  ==== add new scan patter GAZGIZ =============== end

      if ((yy+_row_pattern<=y) && (y<yy+2*_row_pattern))
        total_offset_r=base_offset-row_sector__offset*row_sector-(_scan_pattern==ZIGZAG ? 1: 0);
      row_sector++;
    }

And at line 476

  uint8_t bit_select = x%8;
  if ((_scan_pattern==ZAGGIZ) && ((y%(_row_pattern*2))<_row_pattern))
      bit_select = 7-bit_select;
//  ==== add new scan patter GAZGIZ =============== start
  if ((_scan_pattern==GAZGIZ) && ((y%(_row_pattern*2))<_row_pattern))
      bit_select = bit_select;
//  ==== add new scan patter GAZGIZ =============== end

also add patern Type in line 64
 enum scan_patterns {LINE, ZIGZAG, ZAGGIZ, WZAGZIG, VZAG, GAZGIZ};

**Comment by wardi1971** [comment]
this is updated File 

[PxMatrix.zip](https://github.com/2dom/PxMatrix/files/3737353/PxMatrix.zip)

**Comment by 2dom** [comment]
If I read this correctly it is a ZAGGIZ pattern without the reversed bit order...hence it would be called ZAGZIG :)

Try the latest master with `display.setScanPatter(ZAGZIG) `

**Comment by 2dom** [comment]
Any update on this?

**Comment by 2dom** [comment]
No response ... Closing
