### ISSUE TITLE
Same code is not working with the lib ver 1.6.0

### ISSUE THREAD

**Issue by jorgecis** [2dom/PxMatrix#138]
I have a panel  P3 63x32 from amazon, the code example works fine with my board if I use the version 1.4.0 of your library but doesn't work with the version 1.6.0

  With the version, 1.4.0 works with some flicking issues, but works, with the version 1.6.0 nothing, all LEDs are off. The same code just the lib is different.

**Comment by 2dom** [comment]
Ok...thanks for the feedback. Could you post your code

**Comment by 2dom** [comment]
Really ... 1.6 does not work but the current master does?

**Comment by amcolash** [comment]
Similar here, 1.5 works great with code but 1.6 does not. Have not tested master yet... I was not even able to fully use the test program in 1.6. The test pattern and pixel works, but the "Pixel" text didn't show and I had a blank display (using `display.display(70)`).

More context for me: I am using an esp8266 (adafruit huzzah), arduino 1.8.9, 64x32 led panel. Happy to provide more info if needed.

**Comment by 2dom** [comment]
Please check the master and give feedback if it works ...

**Comment by jorgecis** [comment]
Yes that is correct, 1.6 is not working but 1.5, 1.4 or master works.

  Using esp8266 mini d1, with plataformio

**Comment by 2dom** [comment]
OK thanks ... good to know ... will investigate  issue 137 and then push another release

**Comment by amcolash** [comment]
Yeah looks like `master` is ok for me too

**Comment by hulud** [comment]
I was unable to use the library and tried to debug it for many hours. It seems that only the test patters work properly but nothing else. I am not 100% sure, but I believe the PxMATRIX_buffer does not get written at all. I printed it and saw zeroes at the beggining where there should be non-dark pixels.

**Comment by hulud** [comment]
ok, it seems that the current master is good, but somehow the version available on platformio is broken :(

**Comment by 2dom** [comment]
Ok ... noted ... new release soon
