### ISSUE TITLE
need some help to get things running

### ISSUE THREAD

**Issue by Cyberfly100** [2dom/PxMatrix#14]
Hi,

I am not very familiar with arduino programming, so I hope you excuse my low level questions.
I included the PxMatrix library into a fresh installation of the Arduino IDE via the library manager. I tried running pixeltime.ino on my "P10 (3535) 16x32 - 4S" display hooked up to a amica NodeMCU, but it looks strange.
The 4 in the name made me think the display might be a 1/4 row scan type, so that's how I wired it up according to your instructions. It seems all the leds can light up, but the pattern is somehow mixed up. I attach a video of the pattern_test.ino running. 
I tried to add a line display.setScanPattern(ZIGZAG) after display.begin(4) to test whether it changes anything, but I get a compiling error: 'class PxMATRIX' has no member named 'setScanPattern'.

Any ideas what I might be doing wrong?

Cheers,
Lucas

test pattern: [LINK](https://kth.box.com/v/pixeltime)

**Comment by 2dom** [comment]
Hi,

are you sure you pulled the latest source from github?

Cheers

Dom

**Comment by Cyberfly100** [comment]
I checked the version number of the version that the Arduino IDE pulled for me and it is v.1.0.0.
I also tried to download the latest version from github myself (from the releases tab), but it seems to be the same version and after including library (sketch>>include library>>add .ZIP library) I get the same error if I try to compile the test_pattern file from the folder that was created in the libraries folder (PxMatrix-v1.0.0). Where would I find the setScanPattern function (just so I can check whether my version has it)?

**Comment by 2dom** [comment]
Hi,

please pull the latest master. The releases do not contain those changes yet.

Cheers

Dom

**Comment by Cyberfly100** [comment]
Alright! Now the setScanPattern and setMuxPattern commands work. Thanks for patiently guiding me there :)
After trying around a bit, it seems STRAIGHT and ZAGGIZ give the best result on the pixeltime.ino but it's still not quite working, I think (see pictures).
I thought with a 1/4 row scan display I would not be using the C input. Should I still use the setup line like this: PxMATRIX display(32,16,P_LAT, P_OE,P_A,P_B,P_C); ?

 I uploaded another video of the test_pattern.ino with 
  display.begin(4);
  display.setScanPattern(ZAGGIZ);
  display.setMuxPattern(STRAIGHT);

testpattern: [LINK](https://kth.box.com/v/pixeltimeSTRAIGHTZAGGIZ)

![6](https://user-images.githubusercontent.com/28017534/40586820-be581fe8-61c7-11e8-8ceb-4b4fb0a7a413.jpg)
![1](https://user-images.githubusercontent.com/28017534/40586821-be74dc0a-61c7-11e8-81a3-75c9a01b04fe.jpg)
![2](https://user-images.githubusercontent.com/28017534/40586822-be8e8ccc-61c7-11e8-925a-0ff8a10bdc75.jpg)
![3](https://user-images.githubusercontent.com/28017534/40586823-bea72912-61c7-11e8-8c55-6d7fa55f355b.jpg)
![4](https://user-images.githubusercontent.com/28017534/40586824-bebfe272-61c7-11e8-8d4e-352dcf7c0bd2.jpg)
![5](https://user-images.githubusercontent.com/28017534/40586825-beec4560-61c7-11e8-809b-833d3577d610.jpg)

**Comment by 2dom** [comment]
You will need A-D...

**Comment by Cyberfly100** [comment]
Oh, I get it now and it is also working now :)
In case someone else reads this: I read in the readme that 1/4 row scan only requires A and B input to address the 4 possible rows, but since my display uses STRAIGHT and not BINARY it requires 4 separate pins A, B, C and D to select the current row (which is also mentioned in the readme, but in a paragraph further down). 
Clues for what you should do with your display basically lie in the connector and the name: mine had 4S in the name, which means 1/4 row scan and since it has pins A-D and not only A and B it could have been directly obvious that STRAIGHT should be the correct mode to get it to work. 

Thanks for the help. On to making some fun animations, then.

Cheers!

**Comment by 2dom** [comment]
Glad that it works ... have fun 😀

**Comment by irondylis** [comment]
Hi. I found your project on Hackaday and decided to give it a shot, looks very cool. I bought the LED matrix from the same guys as you on AliExpress, and a NodeMCU board. I'm having a few issues and was hoping you could point me in the right direction. :)

As with Cyberfly's problem, how do you tell if you need A&B or ABCD? My test pattern looks like this:

[https://youtu.be/B0C1g4TqZoQ](url)

I've tried every combo of STRAIGHT/LINE ZIGZAG etc. Currently I'm only using A&B.

Any help appreciated, and thanks for doing the heavy lifting on this. :)

**Comment by 2dom** [comment]
Thanks...I think Lucas summarized it nicely. Your display ist most likely requires STRAIGHT which necessitates A-D. I will update the readme when I find the time.

**Comment by 2dom** [comment]
I updated the readme now

**Comment by irondylis** [comment]
Cheer dude.

display.begin(4);
display.setScanPattern(ZAGGIZ);
display.setMuxPattern(STRAIGHT);

worked with the ABCD connections.

Appreciate your help.

**Comment by Sudiptatito** [comment]
I have another problem when I tried to compile pattern test from library example it's showing "too many arguments" where was the problem?
