### ISSUE TITLE
128x64 display setup

### ISSUE THREAD

**Issue by nathalis** [2dom/PxMatrix#142]
I successfully tested 128x64 (two P3 64x64 Led panels), you need to setup:

// Defines the buffer height / the maximum height of the matrix
#define PxMATRIX_MAX_HEIGHT 64
// Defines the buffer width / the maximum width of the matrix
#define PxMATRIX_MAX_WIDTH 128

PxMATRIX display(128,64,P_LAT, P_OE,P_A,P_B,P_C,P_D,P_E);

display.begin(32);
display.setPanelsWidth(2);

![IMG_20191031_174506](https://user-images.githubusercontent.com/52428568/67967795-8ac9e000-fc06-11e9-8ee8-9eda6d1d8f5d.jpg)

**Comment by 2dom** [comment]
Great :)

**Comment by 2dom** [comment]
Thanks for the info

**Comment by adrianrv** [comment]
I am using a d1 mini pro. Using Wifi to fetch live data and display in 1 screen works great. But as soon I try the same with 2 displays the board crashes.

Which board are you using? In the picture you posted seems to be  esp8266. Are you also fetching live data using the Wifi?

**Comment by nathalis** [comment]
Just set variables in libraries by the instructions. I used NodeMcu ESP8266 Lua WIFI V3, CH340.

**Comment by adrianrv** [comment]
I did, it was the first thing I did while I read the first message. I am trying to understand if there are some limitations with my board (d1 mini pro).

While using the 2 screens are you using also the WIFI library and fetching data from some live source? Can you paste the imports you are using in the example you showed?

**Comment by adrianrv** [comment]
Definitely is too much for the board I am using. Using only the PxMatrix with 2 screens works relative ok (with some ghost pixels). Thanks for the info :)
