### ISSUE TITLE
Only Red light Turning ON

### ISSUE THREAD

**Issue by SimaoRenato** [2dom/PxMatrix#147]
Hey guys, I'm trying to use the lib with a ESP32.

I've manage to find out that my display (a P10 32x16) should work with a 1/4 step, mux pattern STRAIGHT and Scan Pattern ZZAGG.

These configurations made my text and lines appears ok. 

The problem I have is that my display only show the RED LED. 

I've double checked my wiring (also remade it from zero), but it keeps only displaying the RED LED.

Any Thougths?

this is how it looks like https://youtu.be/afklKD1rAIA (yes, image is upside down, sorry for that)

**Comment by SimaoRenato** [comment]
Flat cable broken

**Comment by 2dom** [comment]
Glad you sorted it out :)
