### ISSUE TITLE
could the AVR edition also support the SAMD series?

### ISSUE THREAD

**Issue by kasperv79** [2dom/PxMatrix#149]
`Compiling 'pixeltime_AVR' for 'Adafruit Feather M4 Express (SAMD51)'
 
pixeltime_AVR.ino:7: In file included from
PxMatrix.h: In member function void PxMATRIX::writeRegister(uint16_t, uint8_t)
PxMatrix.h: 471:65: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if ((bit_counter ==  (_send_buffer_size*8 - reg_position-1)))
PxMatrix.h: In member function void PxMATRIX::display(uint16_t)
 
Error compiling project sources
PxMatrix.h: 1070:88: error: 'SPI_TRANSFER' was not declared in this scope
Build failed for project 'pixeltime_AVR'
   SPI_TRANSFER(&(*bufferp)[_display_color][i*_send_buffer_size],_send_buffer_size)
 
PxMatrix.h: 1087:82: error: 'SPI_TRANSFER' was not declared in this scope
   SPI_TRANSFER(&(*bufferp)[_display_color][i*_send_buffer_size],_send_buffer_size)
 
PxMatrix.h: 1128:88: error: 'SPI_TRANSFER' was not declared in this scope
   SPI_TRANSFER(&(*bufferp)[_display_color][i*_send_buffer_size],_send_buffer_size-1)
 
PxMatrix.h: 1138:39: error: 'GPIO_REG_SET' was not declared in this scope
   GPIO_REG_SET( 1 << _SPI_MOSI)
 
PxMatrix.h: 1140:41: error: 'GPIO_REG_CLEAR' was not declared in this scope
   GPIO_REG_CLEAR( 1 << _SPI_MOSI)
 
PxMatrix.h: 1141:36: error: 'GPIO_REG_SET' was not declared in this scope
   GPIO_REG_SET( 1 << _SPI_CLK)
 
PxMatrix.h: 1142:38: error: 'GPIO_REG_CLEAR' was not declared in this scope
   GPIO_REG_CLEAR( 1 << _SPI_CLK)
PxMatrix.h: In member function void PxMATRIX::flushDisplay()
 
PxMatrix.h: 1172:18: error: 'SPI_BYTE' was not declared in this scope
   SPI_BYTE(0x00)
PxMatrix.h: In member function void PxMATRIX::displayTestPattern(uint16_t)
 
PxMatrix.h: 1181:20: error: 'SPI_BYTE' was not declared in this scope
   SPI_BYTE(0xFF)
PxMatrix.h: In member function void PxMATRIX::displayTestPixel(uint16_t)
 
PxMatrix.h: 1228:38: error: 'SPI_BYTE' was not declared in this scope
   SPI_BYTE(1<<_test_pixel_counter%8)`

**Comment by 2dom** [comment]
Don't have access to such an MCU - so not supposed for now - sorry. Wanna give it a shot?
