### ISSUE TITLE
Working with more than 3 panels

### ISSUE THREAD

**Issue by SimaoRenato** [2dom/PxMatrix#151]
Does anyone have used this lib with more than 3 panels?

I'm using a p10 32x16 4row scan/ zzagg pattern / straight mux.

The pattern scan works fine, but pixel time, or even drawing a single white pixel is not working.

If anyone did it before, I appreciate the help.

**Comment by metingul** [comment]
I work with 6 panels (192X16) with older version of PxMatrix library, but current version does not work properly with 4 panels, the RED color is fine but other colors does not work properly.

**Comment by SimaoRenato** [comment]
Whitch version are you using?

**Comment by SimaoRenato** [comment]
Sorry, saw the version rigth after I've hit Comment.

I'll try 1.3.0 to see if works.

for now I'm developing my own library, but not with all resources as PxMatrix has.

**Comment by 2dom** [comment]
We discovered that chaining multiple panels may lead to pixel color shift due to the propagation delay of all the registers in the loop-back signal path

**Comment by 2dom** [comment]
Do you have this problem https://twitter.com/MLE_Online/status/1192265470117695488?s=19 ?

**Comment by EvilArtist** [comment]
> We discovered that chaining multiple panels may lead to pixel color shift due to the propagation delay of all the registers in the loop-back signal path

I have the same problem! Did you have any solution?
Could you share to me. 

Thanks.

**Comment by SimaoRenato** [comment]
I did have to build my own library for the project I did.  It is not as complete as the PxMatrix, but I was able to work with 12 panels in row.

**Comment by vinzzzzz24** [comment]
> I did have to build my own library for the project I did. It is not as complete as the PxMatrix, but I was able to work with 12 panels in row.

Can you share your solved problem here please :( thanks
