### ISSUE TITLE
Can I use the library with a mono color P10 LED?

### ISSUE THREAD

**Issue by mabbas007** [2dom/PxMatrix#154]
I'd love to use your library but want to make sure it's possible before wasting a lot of time trying.

Thanks in advance

**Comment by 2dom** [comment]
Nope ... Not supported atm

**Comment by CTWF** [comment]
No problem. I use P4 16x64 single color 2 panel

**Comment by marryton007** [comment]
@CTWF  Can  you share the  code?  thanks.
