### ISSUE TITLE
issues with p2.5 64x64 160mm panels with ICN2038S drivers HUB75E connections

### ISSUE THREAD

**Issue by Jay-esp** [2dom/PxMatrix#157]
Having a couple of issues.
Connected to esp32 dev1 doit.
Pinout for reference according to supplier.
![hub75e pins](https://user-images.githubusercontent.com/58309071/69828375-f7db9000-121b-11ea-9de4-584674de5f4f.PNG)

When setting the driver to anything other than SHIFT I get this, parts are dim, red lines. This is fixed when I power cycle the display without powering down the esp so it must be an initialization issue.

![IMG_3645](https://user-images.githubusercontent.com/58309071/69828512-6e788d80-121c-11ea-80f0-fb08e1a908ee.JPG)

Now if I change the driver type to SHIFT, I don't have that issue but another one, vertical is offset and for example line 31 appears on line 30 and line 31 is on 33.

![IMG_3646](https://user-images.githubusercontent.com/58309071/69828725-4dfd0300-121d-11ea-903b-eaebc1277205.JPG)

Any idea?
Other point, the esp crashes very often and reboots
./home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1446 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x400890ef on core 1

Using esp32 plus rtc module and wifi webserver.

**Comment by xsrf** [comment]
Guess it's the same issue as with https://github.com/2dom/PxMatrix/issues/101
Using `SHIFT` should be correct... Can you try with `setFastUpdate(false)`?

**Comment by Jay-esp** [comment]
have not worked on this project for some months, will check once I take it on again, I suspect the issue might be that I don't use level shifters and hi-lo logic levels are marginal, I solved some of the issues by reducing the voltage to the lcd panel

**Comment by Nikitok122** [comment]
Hi!! I have the same panel, but cant make it to work. The issue is doubling the screen. can u share your code from this example??

**Comment by Nikitok122** [comment]
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/img/text-ghosting.jpg about your problem

**Comment by Jay-esp** [comment]
Hi, I ended up using other libraries but had similar issues, solved for now by reducing the 5V voltage to the panel a little bit to get the 3.3V signal from the esp in range of proper 0 and 1 detection by the panel, you might want to recheck the wiring first
