### ISSUE TITLE
Merry XMas! Thank You 2Dom ;-)

### ISSUE THREAD

**Issue by Robotech-e** [2dom/PxMatrix#162]
I want to thank you because of your excellent work with this library, now we can work with ATMEL too ;-)

Merry XMas and have a very Happy New Year 2020!

https://youtu.be/6CMpJks16Ow

![PHOTO_20191224_171742](https://user-images.githubusercontent.com/54823253/71426590-95867b80-2671-11ea-9fa6-18adf8229509.jpg)

**Comment by 2dom** [comment]
Thanks Robotech-e! My pleasure ... All the best for you an your family for 2020 too 😀

**Comment by Robotech-e** [comment]
![arduino_xmas4](https://user-images.githubusercontent.com/54823253/71492671-be884700-27fe-11ea-8306-d3189e4cb1ed.jpg)
![arduino_xmas6a](https://user-images.githubusercontent.com/54823253/71492672-be884700-27fe-11ea-96b1-4c4dc5bf8719.jpg)
