### ISSUE TITLE
README.txt is confusing

### ISSUE THREAD

**Issue by needfulthing** [2dom/PxMatrix#163]
Hi, I have problems following the instructions in the README.txt file:

- "Check that the Adafruit_PCD8544 folder contains Adafruit_PCD8544.cpp and Adafruit_PCD8544.h"

This leaves me completely blank. I can not see this folder in the downloaded ZIP nor do I have this folder on my drive. Searching for it I found it is the Adafruit PCD8544 Nokia 5110 LCD Library. Is this another library your library depends on besides the Adafruit GFX library? If so, it should be clearly stated in the description ("need this, download here, install there").

- This made me just wondering: rename folder to "P10_matrix". If everybody has to rename it, why not name it correctly in the ZIP in the first place?

Thank you and kind regards

**Comment by 2dom** [comment]
yeah ... well spotted. This file is simply wrong - please ignore. Will update

**Comment by needfulthing** [comment]
Thank you :)
