### ISSUE TITLE
working with more then 4 panels

### ISSUE THREAD

**Issue by nareshmekh3** [2dom/PxMatrix#165]
Hi thank you so much  for the great library,
Right now i am able to connect 4 rgb panels 32x32(1/16 scan rate) its working fine. if i need to connect 4 more panels thus this library supports, please let me know if anyone tested it.
 how many panels can be connected at the maximum???

**Comment by 2dom** [comment]
I don't think much more than 4 will work, Some people have struggled with 3. The problem is that the signals propagate through lots of panels / driver chips which adds delay. By using the loop-back at some point clock and data don't match up anymore leading to color shift.
