### ISSUE TITLE
Text 5 lines / font size

### ISSUE THREAD

**Issue by Alexxx2005** [2dom/PxMatrix#167]
Hello 2dom,

thank you for your Library it's very good but i have a Problem
with the Code for a normal Text , i use this Code 

`#include <PxMatrix.h>
#include <Ticker.h>
Ticker display_ticker;
#define P_LAT 16
#define P_A 5
#define P_B 4
#define P_C 15
#define P_D 12
#define P_E 0
#define P_OE 2

// Pins for LED MATRIX
//PxMATRIX display(32,16,P_LAT, P_OE,P_A,P_B,P_C);
//PxMATRIX display(32,32,P_LAT, P_OE,P_A,P_B,P_C,P_D);
//PxMATRIX display(64,64,P_LAT, P_OE,P_A,P_B,P_C,P_D,P_E);
PxMATRIX display(64,32,P_LAT, P_OE,P_A,P_B,P_C,P_D);

// ISR for display refresh
void display_updater()
{
// display.displayTestPattern(70);
// display.displayTestPixel(70);
 display.display(70);
}

uint16_t myGelb = display.color565(255, 255, 0);
void setup() {
// put your setup code here, to run once:
Serial.begin(9600);
display.begin(16);
display.flushDisplay();
  display.setTextColor(myGelb);
  display.setCursor(2,0);
  display.print("Alexander");
  display.setTextColor(myGelb);
  display.setCursor(2,8);
  display.print("AlexanderM");

display_ticker.attach(0.002, display_updater);
delay(1000);
}

void loop() {
delay(100);
}`

What i have to do 

1. if i want to make the font Smaller ?
2. or text with five or six lines ?
3. or a running font

It gaves examples or instructions ?

Thank you so much , best regards Alex

**Comment by 2dom** [comment]
PxMatrix includes AdafruitGFX - check their docs... setFontSize and setFont
