### ISSUE TITLE
32x16 pixeltime not displaying correctly

### ISSUE THREAD

**Issue by themakerbro** [2dom/PxMatrix#168]
Hey, thanks for the awesome library. The scan pattern looks good with the default options, but rows 5–8 and 13–16 do not display. Any clues as to what's going on? See attached pic for reference, thanks!

![IMG_2D703CD97B8E-1](https://user-images.githubusercontent.com/7302561/72956866-44dc6e00-3d56-11ea-9fca-db4f4651f6b0.jpeg)

**Comment by kushalsharma07** [comment]
what was the fault? i am having same problem

**Comment by themakerbro** [comment]
run power cables between the Px molex connector and the microcontroller (in my case).
