### ISSUE TITLE
Second half of panel problem

### ISSUE THREAD

**Issue by frits79** [2dom/PxMatrix#172]
Hello,

I'm using an ESP32 with a led panel, but i have a small problem. From line 17 (from top to bottom) all pixels have moved 1 to the right as you can see on the picture.  What can be the problem? (i'm using 2 panels of 64x32).
Thank you in advance.

![LEDpanel](https://user-images.githubusercontent.com/60572519/73608508-38f97300-45c4-11ea-81dd-88e43f9fdd04.jpg)

**Comment by 2dom** [comment]
Can you post your code?
