### ISSUE TITLE
Black panel between frames when not delaying

### ISSUE THREAD

**Issue by needfulthing** [2dom/PxMatrix#173]
Hi 2dom, I run your library on a 64x32 matrix display and an ESP8266. Unfortunately the panel goes completely black after drawing an image when I do not include a returning delay in the loop. See my code here https://github.com/needfulthing/LED-Matrix-Display-Examples/blob/master/LED_Panel_64x32_Lava_Lamp_Effect.ino. I can update properly with a delay(1) after every panel row but without the delay, I get a horrible strobe effect. Do you have any idea why?

**Comment by 2dom** [comment]
yeah ... you will have to put some day in loop. Otherwise the CPU is never idle and cannot execute the timer routine that is driving the display properly.
