### ISSUE TITLE
ESP32 pinout unclear

### ISSUE THREAD

**Issue by awyork** [2dom/PxMatrix#176]
Please see https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf#page=8

The instructions are unclear if the pin number is the actual pin number in the diagram (the pinout of the attached PDF) or the GPIO number.

Ex: The CLK is connected to either GPIO 14 (which is pin 13)  or pin 14 (which is GPIO 12)

Hopefully the instructions are referring to the GPIO number.

**Comment by sovcik** [comment]
It's GPIO 14

**Comment by awyork** [comment]
Got this figured out.  The pinout will be the board's pinout.   The Arduino IDE will take care of any other mapping.

**Comment by 2dom** [comment]
Added keyword GPIO to Readme - thanks for pointing it out!
