### ISSUE TITLE
pixletime example has bad #define

### ISSUE THREAD

**Issue by awyork** [2dom/PxMatrix#177]
https://github.com/2dom/PxMatrix/blob/master/examples/pixeltime/pixeltime.ino

Line 14:
//#define PxMATRIX_SPI_FREQEUNCY 20000000

Should be:
//#define PxMATRIX_SPI_FREQUENCY 20000000
  
"E" and "U" are transposed in the word frequency

**Comment by awyork** [comment]
Also, setting the frequency does not seem to work.

I changed line 14 in pixeltime as below but I still see 20Mhz on the 'scope.

// Defines the speed of the SPI bus (reducing this may help if you experience noisy images)
#define PxMATRIX_SPI_FREQUENCY 5000000

**Comment by 2dom** [comment]
OK .. fixed the example. Still strange that it does not effect the actual speed. Any ideas?

**Comment by awyork** [comment]
> OK .. fixed the example. Still strange that it does not effect the actual speed. Any ideas?

Sorry, I accidentally fried my eval board.  I've been waiting on a shipment from China.  I'll get back to you.

**Comment by 2dom** [comment]
OK ... re-open when the issue persists...
