### ISSUE TITLE
Cant get red blue and green to line up

### ISSUE THREAD

**Issue by slowsauce** [2dom/PxMatrix#178]
![20200225_151615](https://user-images.githubusercontent.com/48930261/75284380-a921a000-57e2-11ea-94cf-bf50718bfbe4.jpg)
Im using pixel time example and getting wrong colors. The red blue and green channel of rbg are split apart. Ex white will have a pixel on as red then 2 over green then 2 over

**Comment by 2dom** [comment]
Code?

**Comment by slowsauce** [comment]
I posted this from phone and am not near computer. It's the example code pixeltime with screen size configured as 64x32 with d and e connected though in testing d seems to not change anything. Also after watching some videos on these types of display I feel I may have 2 duds because they seem to only work at 3.3v not 5. At 5v the blue and green led stop putting out light.

**Comment by 2dom** [comment]
You could try setting the horizontal resolution to 65 ...

**Comment by slowsauce** [comment]
found problem, it was a faulty cable between output of esp and display, the cable wires were super high resistance on only some pins, i had 3 of the cables and each had issue.
