### ISSUE TITLE
Support for panels with HC138 address decoder

### ISSUE THREAD

**Issue by andreacampanella** [2dom/PxMatrix#2]
Someone donated us 54 panels and I would like to use PxMatrix with them , but they are wired in a very odd way (more [info here](https://wiki.london.hackspace.org.uk/w/index.php?title=LED_tiles_V2&oldid=50969) ) , I already wrote some code for them but I'm struggling with the color mixing , would be very very helpful if PxMatrix would support this kind of panel.

**Comment by SDI-SoftwareDefinedInverter** [comment]
Just had a look ... these work completely different than any of the Chinese made panels I have seen so far. This would require a very different driver - so I don't think I will be able to support them anytime soon (sorry).
