### ISSUE TITLE
Using more than 128x32 pixels

### ISSUE THREAD

**Issue by ElectricDesigns** [2dom/PxMatrix#21]
I wanted to use a strain of four 64x32 panels. But the library seems to stop working after I added the third panel to the declaration.

When I declare the width as (128, 32) it works and does everything as it should. Even when I connect the third panel it displays everything over all three of the displays. But if I declare the true size (192,32) it just stops working altogether. Is this a limitation of the library or am I declaring it wrong?

**Comment by 2dom** [comment]
Yes ... there is a limitation regarding the frame buffer size. It is currently limited to 4096 pixel. You can easily increase that by modifying  

```
#define max_matrix_height 64
#define max_matrix_width 64

```
in the pxmatrix.h file. In your case 

```
#define max_matrix_height 192
#define max_matrix_width 32

```
should work.

**Comment by ElectricDesigns** [comment]
I found those statements in the pxmatrix.cpp file. I changed it and will test it in a bit. Thank you!

**Comment by 2dom** [comment]
... you seem do be on an old version of the library ... you may want to check out the current master

**Comment by ElectricDesigns** [comment]
Indeed I was, now it is in the location you specified.
