### ISSUE TITLE
Tip: Convert animated GIF to RGB565 byte array for use with PxMatrix

### ISSUE THREAD

**Issue by toblum** [2dom/PxMatrix#246]
Hi @2dom,

this issue ist just to let you (and possible others) know that I made a online converter for animated GIFs to the RGB 565 byte array format used by your black_lives [example](https://github.com/2dom/PxMatrix/tree/master/examples/black_lives).

I wasn't able to make the provided scripts work in my environment, so I created a online converter. I thought this might be useful for others, so I published it at github.

You can find it here: https://toblum.github.io/gif2carray/

I will close this issue after posting.

Best regards
Tobias

**Comment by 2dom** [comment]
Cool 😎 thanks for sharing Tobias
