### ISSUE TITLE
Brightness setup

### ISSUE THREAD

**Issue by pargit** [2dom/PxMatrix#25]
Hi, 
is there a way to control the brightness of the panel?
i searched but couldn't  find any info about it.

thanks
Mor

**Comment by 2dom** [comment]
Nope ... so far a adjusted brightness via the value x in `display.display(x)`. However, this won't work if you use `display.setFastUpdate(true)`.
I will implement a `display.setBrightness(x)` function when I find the time.

**Comment by 2dom** [comment]
this is the on-time of the display while scanning in microseconds but only for setFastUpdate(false)

**Comment by prof955** [comment]
you are doing Brightness adjust actually while creating test grid:

display.drawLine(xx+16,0,xx+16,5,display.color565(xx*16,0,0));
 
can't we implement this as an setting for all display?

**Comment by vasquezj-ibm** [comment]
A brightness function would be great when you get time and thanks for the consideration

**Comment by 2dom** [comment]
Yes ... brightness is not a biggie ... will do when I have the time

**Comment by 2dom** [comment]
Ok ... check out the current master. I also updated the example so you can see how it is being used.
