### ISSUE TITLE
White pixels are splitted to red, green and blue when 2 (internally chained) panels are chained

### ISSUE THREAD

**Issue by lg007** [2dom/PxMatrix#274]
Hello,

I am using the pxmatrix v1.8.2 and an ESP32 to drive 2 pcs. of Q5E8V3H P5 64x32 RGB displays. The panel seems to be an internally chained 2 panel display, therefore in order to drive it, I need to set `display.setPanelsWidth(4);`. But here comes the problem that others have experienced as well; white pixels are split to red, green and blue pixels, being one or two pixels apart of each other (depending on where they are in the chain). Is there a solution to this (using the pxlibrary)? I tried to find a solution to this in the issues (both closed and open), but I haven't found a real solution. Any ideas are welcome! 

Regards,

**Comment by 2dom** [comment]
This is probably due to misalignment of clock and data - a known artifact of using this matrix library and the loop-back method of connecting them. I suggest to use ESP32 and another parallel display library
