### ISSUE TITLE
Ghosting Issue

### ISSUE THREAD

**Issue by ToXIcGaming** [2dom/PxMatrix#28]
So I have the same panel as [here](https://github.com/2dom/PxMatrix/issues/5) and am using the options detailed there.

The issue im having is ghosting with text and icons (well it looks kinda like ghosting), [here](https://imgur.com/a/ww2Heab) are some pics.

Also appears to be some colour issues too.

**Comment by ToXIcGaming** [comment]
Here is the pinout
![Pinout](https://i.imgur.com/2BNF7fl.jpg)

and [here](https://gist.github.com/ToXIcGaming/c898f9c670cace0af30cb427d402c4c9) is the code.

**Comment by ToXIcGaming** [comment]
@2dom any idea?

**Comment by 2dom** [comment]
Sorry for the delay ... very busy atm. Can you run the pattern test and post the result (I will need two fully red,yellow,white cycles.

**Comment by Xonotron** [comment]
I also have an issue with my panel, this might be related. It's not really ghosting but some columnish crosstalk issue maybe?

I took an overexposed picture to make it clear. To the naked eye, the dim green pixels are only barely visible but there:

![pixelcolumncrosstalk](https://user-images.githubusercontent.com/42165943/43758077-4c074400-9a1b-11e8-8831-4ada326cdaed.jpg)

It's also visible in this video, the guy uses PxMatrix but a different panel. So it's propably eighter a bug or a general hardware issue with this kin of panels.?

![pixelcolumncrosstalk2](https://user-images.githubusercontent.com/42165943/43758562-c3b17646-9a1c-11e8-8242-2bef0c7bf98d.jpg)

**Comment by 2dom** [comment]
@Xonotron did you try setFastUpdate(true). This would change the timing

**Comment by ToXIcGaming** [comment]
Sorry for the late reply, I was away.

[Here](https://i.imgur.com/zUtbd48.gifv) is the result of the pattern test.
I flipped the image because I accidentally had the panel upside down.

**Comment by 2dom** [comment]
For some reason it enables all 4 rows at a time. Are you running this on ESP32 or ESP8266?

**Comment by 2dom** [comment]
Looks like a hardware/connectivity issue. To test this disconnect A,B,c,d from the esp and connect A to gnd, b,c,d to vcc. Then re-run the pattern test. You should see a single line.

**Comment by ToXIcGaming** [comment]
Doing that produces [this](https://i.imgur.com/kliUwzT.gifv).

**Comment by 2dom** [comment]
Ok...looking good. Somehow the abcd signals do not reach the matrix...things to try: measure on esp pins with multimeter (a should be low on first pass of pattern test, others high, then b low and so on). Check solder points on esp. try different gpios.

**Comment by Xonotron** [comment]
@2dom Yes, this is with setFastUpdate(true).

**Comment by ToXIcGaming** [comment]
So I appear to have fixed it but I dont really know how, I ran the code from the thread I originally linked and it worked.
