### ISSUE TITLE
Only red and no lower half screen

### ISSUE THREAD

**Issue by nygma2004** [2dom/PxMatrix#285]
I am making displays, so I have a few P6 boards (exact marking P6-L-192X192-2019) and a matching Wemos D1 mini ESP8622 based boards. Last time I built my code was probably a year ago.
Today, I compiled and uploaded a new code I noticed the following: only the top half of the screen is showing, and the only in color red. And it is the same for my code, or the pattern_test or Aurora_demo. Top half shows geometrically correctly but only in red. The bottom half of the screen is just blank, and I never see any colors other than red. If I accidentally touch the HUB75 terminals with my finger other colors and bottom half of the screen lights up, so the screen is not broken.

My declaration is the following:
`
PxMATRIX display(32,32,P_LAT, P_OE,P_A,P_B,P_C,P_D);
`
and the rest of the display setup looks like this:
```
    // P6-L-192X192-2019
    display.begin(8);                      // 1/8 scan display
    display.setFastUpdate(true); 
    display.setScanPattern(LINE);          
    display.setColorOrder(RRGGBB);        
```

If I change anything, it just make it worse. If I change the scan line the gets misaligned, fastUpdate makes no difference, ScanPattern obviously makes the top of the display wrong and ColorOrder makes absolutely no effect.

So I don't think there is any issues with the lib, but I just can't figure out what I have done wrong. Could it be that other libraries are causing this?

**Comment by nygma2004** [comment]
I dig up another P6 board (which says P6-3535-2018-G) which has a slightly different declaration:
```
    // P6-3535-2018-G
    display.begin(8);                      // 1/8 scan display
    display.setFastUpdate(true); 
    display.setScanPattern(WZAGZIG );          
    display.setColorOrder(BBGGRR);     
```
This again only shows the top half of the screen, but this is in only in blue. Top half is geometrically correct.

**Comment by nygma2004** [comment]
I am sorry, but it was a cable problem. It looks like the J1, J2 ribbon cable was bad, and it works fine after it got replaced. I never though a simple thing can cause such issue.

**Comment by Gisleburt** [comment]
Thank you @nygma2004! I had the same problem and don't think I'd have worked it out myself.
