### ISSUE TITLE
Odd panel config

### ISSUE THREAD

**Issue by opticron** [2dom/PxMatrix#29]
I just got another set of 1/8 scan 32x32 panels from China and the're even weirder than the first set I got. I've poked at the lib trying to find settings that will make it work right, but I figured I'd ask. Do we have settings that can handle this kind of pattern: https://photos.app.goo.gl/kzqTATvhVoxiHZGy9 ?

**Comment by shodan45** [comment]
I **think** my 32x32 panel is doing the same:

https://photos.app.goo.gl/gFottGJd43rvuzQA8

I bought mine from Sparkfun, if that helps.

**Comment by opticron** [comment]
Yours is doing something different from mine, but still weird and probably currently unsupported.

**Comment by opticron** [comment]
@shodan45 Alright, I have some code to test tomorrow which should contain the solutions for both our panel setup issues. I'll let you know once I've verified it works for mine.

**Comment by opticron** [comment]
@shodan45 when you get a chance, could you test against my fork with setScanPattern(VZAG) ? https://github.com/opticron/PxMatrix

**Comment by opticron** [comment]
@shodan45 I just pushed another commit, pull it and give it a try. Happy to help, these height/pattern=4 panels are getting pretty damn weird.

**Comment by shodan45** [comment]
That almost did it. I thought all that was needed was to fix the "y chunks" problem, but the X axis isn't right either. It seems to be mapping to 16-31, then 0-15.

`      display.drawPixel(0, 0, myRED);
      display.drawPixel(16, 0, myYELLOW);
      display.drawPixel(31, 0, myGREEN);
` gives:
![img_20180812_233531](https://user-images.githubusercontent.com/5125174/44013140-60101aa4-9e89-11e8-8452-f3744960127e.jpg)

I stuck a quick hack of `x -= 16; if (x < 0) x += 32;` in there, and that fixed it, but I'm sure that's not the best way to fix it.

**Comment by opticron** [comment]
Alright, I'll update my branch and the PR today with the right values.

**Comment by shodan45** [comment]
Odd, that didn't seem to do anything... I double checked that I have the latest version, and I do. It's still doing the 16-31, 0-15 thing on the X axis.

**Comment by opticron** [comment]
Alright, well I just inverted the X blocks again on my branch just for good measure. Hopefully that gets it done. Last time I simplified some code in the process and may have ended up inverting things twice.

**Comment by shodan45** [comment]
That seems to have fixed it! Thank you!!
