### ISSUE TITLE
Wiring issues of P10 RGB over PxMatrix with no indications

### ISSUE THREAD

**Issue by sohamchatterjee98** [2dom/PxMatrix#298]
Hello everyone,

I was using one of the examples of Px Matrix library.
The pannel was a P10 board and I tried it with ESP32.
Now I found it hard to wire it up because there was nothing, no pinout literally written or given anywhere so it became very hard.
Somehow when I managed to get through all that I saw that there was not much information available on the wiring part and with what little I could do I managed to print a "Welcome to Px Matrix!" But it was not RGB but just blue..

Can anyone help me understanding what's going wrong?
  
Thanks to anyone who is reading.

![p10-outdoor-led-module-green-al-quraish-electronics-and-original-imafvyjpdtrtdurh](https://user-images.githubusercontent.com/63398994/169889038-1938a84a-a077-41c7-860b-6d42713bedc4.jpeg)

**Comment by RennySakuto** [comment]
You can search the pins graph on GOOGLE about ESP32 and HUB75. By the way, some P10 boards using HUB08. 
If there are letter show on the screen but lack of color, check the R1, G1 B1 data inputs
