### ISSUE TITLE
P3 196*196 with driver ICN2037BP not worked

### ISSUE THREAD

**Issue by brainhasan** [2dom/PxMatrix#303]
I used Arduino Nano 168 and P3 from china
1. my Code was the example in Pixeltime_AVR
2.  that is the image of HUB75 , it has just ABCE , no D pin 
![IMG_20220922_125000](https://user-images.githubusercontent.com/24478162/191728830-d8515459-582e-4784-84cd-b66a163cea1e.jpg)
![IMG_20220922_124812](https://user-images.githubusercontent.com/24478162/191728838-cf0b99dc-092c-4c0b-bb81-35d739dfddf3.jpg)
![IMG_20220922_124819](https://user-images.githubusercontent.com/24478162/191728842-21e33283-50d8-410e-b486-7b05b487313a.jpg)

3- i connect it 
<html>
<body>

PI | PO
-- | --
R2 | R1
G1 | R2
G2 | G1
B1 | G2
B2 | B1

<html>
<body>

PI | NANO
-- | --
A|2
B|3
C|4
D| no D pin
E| 6
STB/LAT| 7
P_OE| 8
CLK |13
R1 |11

</body>
</html>

4.  i get nothing on the panal , when i disconnect the power from the NANO the panel show 2 lines in number 0 and number 33

**Comment by fragmation** [comment]
the third pint from down (right side) is D erroneous marked on silk GND

**Comment by 652626737** [comment]
Hello, have you successfully driven the LED?

**Comment by fragmation** [comment]
> Hello, have you successfully driven the LED?

yup the panel are working with simple gifs :D :D
