### ISSUE TITLE
New Panel 128x64 1/32 ABC type panel with 5658 chips

### ISSUE THREAD

**Issue by Phil1972** [2dom/PxMatrix#319]
Hi,

https://www.aliexpress.com/item/1005001803754216.html?spm=a2g0o.order_list.order_list_main.9.21ef1802vWszXc

It seems I ordered that panel without checking the entire details of it. So I contacted the vendor and he mentioned that this panel is driven by 5658 chips.  There is only one input on this one and so I cannot connect the output to the input to shift RGB from the output to the input as mentionned in the instructions here.

So my question is, can I make this one work?  How would I connect the RGB pins?

D,E are grounded here, so only ABC are available.

Chips:
8x VB5658 - HI55502231A
16x ICN2037BP
4x 74HC245

thanks for your time,

![image](https://user-images.githubusercontent.com/40364427/229310482-f5e46912-9c7f-4f5d-a0b5-c2b804d101f3.png)

**Comment by mzashh** [comment]
i would suggest trying this library instead as its much more feature rich and actively maintained https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA

**Comment by mzashh** [comment]
also i would first check whether the N pins are grounded or not, if not then the one next to C is D pin and the other one is E

**Comment by Phil1972** [comment]
Hi guys,

@2dom are you saying this panel is now supported? :)

thanks,
