### ISSUE TITLE
I can't understand the pattern test runs successfully problem.

### ISSUE THREAD

**Issue by sercanbayikli** [2dom/PxMatrix#320]
Hello, I am using a P8 LED display:
![024d5808-7c0b-4880-a9c2-3d0a7a7de141](https://user-images.githubusercontent.com/64726253/229366211-f16a73d9-dcb4-4238-a14b-c36f2a2e5d61.jpg)

`#include <PxMatrix.h>

#ifdef ESP32

#define P_LAT 22
#define P_A 19
#define P_B 23
#define P_C 18
#define P_D 5
#define P_E 15
#define P_OE 16
hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;

#endif

#ifdef ESP8266

#include <Ticker.h>
Ticker display_ticker;
#define P_LAT 16
#define P_A 5
#define P_B 4
#define P_C 15
#define P_D 12
#define P_E 0
#define P_OE 2

#endif
// Pins for LED MATRIX

PxMATRIX display(40,20,P_LAT, P_OE,P_A,P_B,P_C);
//PxMATRIX display(64,32,P_LAT, P_OE,P_A,P_B,P_C,P_D);
//PxMATRIX display(64,64,P_LAT, P_OE,P_A,P_B,P_C,P_D,P_E);

#ifdef ESP8266
// ISR for display refresh
void display_updater()
{
  display.displayTestPattern(70);
  // display.displayTestPixel(70);
  //display.display(70);
}
#endif

#ifdef ESP32
void IRAM_ATTR display_updater(){
  // Increment the counter and set the time of ISR
  portENTER_CRITICAL_ISR(&timerMux);
  //isplay.display(70);
  display.displayTestPattern(70);
  portEXIT_CRITICAL_ISR(&timerMux);
}
#endif

uint16_t myCYAN = display.color565(0, 255, 255);
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
  display.begin(5);
  display.flushDisplay();
  display.setTextColor(myCYAN);
  display.setCursor(2,0);
  display.print("Pixel");
  Serial.println("hello");

  #ifdef ESP8266
    display_ticker.attach(0.004, display_updater);
  #endif

  #ifdef ESP32
    timer = timerBegin(0, 80, true);
    timerAttachInterrupt(timer, &display_updater, true);
    timerAlarmWrite(timer, 4000, true);
    timerAlarmEnable(timer);
  #endif

  delay(1000);
}

void loop() {

 delay(100);

}`

I am doing pattern test using this code.

https://user-images.githubusercontent.com/64726253/229366466-ff69f662-657c-434b-bcba-d92788860d56.mp4

From what I understand, the test seems successful.

`#include <PxMatrix.h>

#ifdef ESP32

#define P_LAT 22
#define P_A 19
#define P_B 23
#define P_C 18
#define P_D 5
#define P_E 15
#define P_OE 16
hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;

#endif

#ifdef ESP8266

#include <Ticker.h>
Ticker display_ticker;
#define P_LAT 16
#define P_A 5
#define P_B 4
#define P_C 15
#define P_D 12
#define P_E 0
#define P_OE 2

#endif
// Pins for LED MATRIX

PxMATRIX display(40,20,P_LAT, P_OE,P_A,P_B,P_C);
//PxMATRIX display(64,32,P_LAT, P_OE,P_A,P_B,P_C,P_D);
//PxMATRIX display(64,64,P_LAT, P_OE,P_A,P_B,P_C,P_D,P_E);

#ifdef ESP8266
// ISR for display refresh
void display_updater()
{
  //display.displayTestPattern(70);
  // display.displayTestPixel(70);
  display.display(70);
}
#endif

#ifdef ESP32
void IRAM_ATTR display_updater(){
  // Increment the counter and set the time of ISR
  portENTER_CRITICAL_ISR(&timerMux);
  //isplay.display(70);
  display.displayTestPattern(70);
  portEXIT_CRITICAL_ISR(&timerMux);
}
#endif

uint16_t myCYAN = display.color565(0, 255, 255);
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
  display.begin(5);
  display.flushDisplay();
  display.setTextColor(myCYAN);
  display.setCursor(2,0);
  display.print(".");
  Serial.println("hello");

  #ifdef ESP8266
    display_ticker.attach(0.004, display_updater);
  #endif

  #ifdef ESP32
    timer = timerBegin(0, 80, true);
    timerAttachInterrupt(timer, &display_updater, true);
    timerAlarmWrite(timer, 4000, true);
    timerAlarmEnable(timer);
  #endif

  delay(1000);
}

void loop() {

 delay(100);

}`

I am using this code. "." I'm trying to type and the screen looks like this.

![WhatsApp Image 2023-04-02 at 19 41 39](https://user-images.githubusercontent.com/64726253/229366704-24d5b736-2191-4328-a863-1d6a30ecb7ab.jpeg)

`Serial.begin(9600);
  display.begin(5);
  display.setPanelsWidth(2);`

What might be causing this problem? Thinking that the panel consists of two parts, I added this code, but the result did not change.

![WhatsApp Image 2023-04-02 at 19 45 11](https://user-images.githubusercontent.com/64726253/229366873-c0a38984-c921-455f-8277-7240accc91bf.jpeg)

![image](https://user-images.githubusercontent.com/64726253/229366888-fcb4b749-fb82-40c3-b5d5-b6386fc4f013.png)

All my cable connections are like this.

**Comment by ainxs** [comment]
U can try using Scan Pattern on library code. display.setScanPattern(x) where x={LINE, ZIGZAG,ZZAGG, ZAGGIZ, WZAGZIG, VZAG, ZAGZIG, WZAGZIG2}.
you can try them one by one

**Comment by sercanbayikli** [comment]
> U can try using Scan Pattern on library code. display.setScanPattern(x) where x={LINE, ZIGZAG,ZZAGG, ZAGGIZ, WZAGZIG, VZAG, ZAGZIG, WZAGZIG2}. you can try them one by one

I tried all of these. But it didn't. I talked to the seller I bought the screen from. The screen works very differently. It works by scanning vertically.


I want to ask another question.

**The screen brightness is very low, the brightness value is at maximum, but I can't get the performance I want. I am using Nodemcu v3. I think I'm having this problem because the output pins are 3v.**

https://market.samm.com/sparkfun-logic-level-converter-bi-directional-en

Can I try to increase the output power to the panel with 5v and solve the brightness problem?

**Comment by mzashh** [comment]
i would suggest trying this library, i had the same brightness problem with this library

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA
try all the various examples and see if those work

if not you can try my modified version of that library and this particular example and see if that works

https://github.com/mzashh/ESP32-HUB75-MatrixPanel-DMA/tree/master/

example
https://github.com/mzashh/ESP32-HUB75-MatrixPanel-DMA/tree/master/examples/One_Eight_1_8_ScanPanel
