### ISSUE TITLE
Overwrite text...

### ISSUE THREAD

**Issue by foskolo** [2dom/PxMatrix#323]
Hi!

I bought this panel: https://is.gd/HBZ580 and it works well.
Now I would like to overwrite some text coming from my MQTT-server. These are values of some sensors that change every few seconds.
The problem is, that the new values don't overwrite the old ones. The pixel of the old values remain on. How can I overwrite them?
I red that this library has to be used with the GFX library of Adafruit to draw lines, circles and so on. But how can I do that? I didn't find any examples.

Thank you!

**Comment by tucsilg** [comment]
Hello a trying a help but i not a master in coding :) In my case if arrived payload from MQTT (in mqtt callback function) drawing a black rectangle where printing text, and in loop cycle printing arrived info...

void callback(char* topic, byte* payload, unsigned int length) {
  mqttpayload="";
    for (int i = 0; i < length; i++) {
    mqttpayload=mqttpayload+(char)payload[i];
  }
  Serial.print("Mqttpayload : ");
  Serial.println(mqttpayload);
  display.fillRect(0,16,PxMATRIX_MAX_WIDTH,PxMATRIX_MAX_HEIGHT, myBLACK);
}

and this is in loop()
  display.setTextColor(myCOLOR2);
  display.setTextSize(1);
  display.setCursor(3,PxMATRIX_MAX_HEIGHT-8);
  display.print(mqttpayload);

I think so helped....

PS: Sorry for my english :)

**Comment by 2dom** [comment]
display.clearDisplay() before writing to the matrix should do the trick ...
