### ISSUE TITLE
The screen looks like it's split in half.

### ISSUE THREAD

**Issue by sercanbayikli** [2dom/PxMatrix#327]
`#include <PxMatrix.h>

#ifdef ESP32

#define P_LAT 22
#define P_A 19
#define P_B 23
#define P_C 18
#define P_D 5
#define P_E 15
#define P_OE 16
hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;

#endif

#ifdef ESP8266

#include <Ticker.h>
Ticker display_ticker;
#define P_LAT 16
#define P_A 5
#define P_B 4
#define P_C 15
#define P_D 12
#define P_E 0
#define P_OE 2

#endif
// Pins for LED MATRIX

PxMATRIX display(32, 16, P_LAT, P_OE, P_A, P_B, P_C);

#ifdef ESP8266
// ISR for display refresh
void display_updater()
{
  display.displayTestPattern(70);
  // display.displayTestPixel(70);
  //display.display(70);
}
#endif

#ifdef ESP32
void IRAM_ATTR display_updater(){
  // Increment the counter and set the time of ISR
  portENTER_CRITICAL_ISR(&timerMux);
  //isplay.display(70);
  display.displayTestPattern(70);
  portEXIT_CRITICAL_ISR(&timerMux);
}
#endif

uint16_t myCYAN = display.color565(0, 255, 255);
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
  display.begin(8);

  
  display.flushDisplay();
  display.setTextColor(myCYAN);
  display.setCursor(2,0);
  display.print("Pixel");
  Serial.println("hello");

  #ifdef ESP8266
    display_ticker.attach(0.004, display_updater);
  #endif

  #ifdef ESP32
    timer = timerBegin(0, 80, true);
    timerAttachInterrupt(timer, &display_updater, true);
    timerAlarmWrite(timer, 4000, true);
    timerAlarmEnable(timer);
  #endif

  delay(1000);
}

void loop() {

 delay(100);

}`

I am using the above code and trying to test the screen.

https://github.com/2dom/PxMatrix/assets/64726253/ee1e71c2-25c8-4443-87a6-8db4433640ee

The screen looks like in the video.
When I try to write, the screen looks like this.

`   
  display.setTextColor(GREEN);
  display.setCursor(2, 0);
  display.print("ABCDE");
  display.setTextColor(GREEN);
  display.setCursor(2, 8);
  display.print("ABCDE");
`

![test](https://github.com/2dom/PxMatrix/assets/64726253/529fd372-2c98-4ef1-9050-653779952599)

I did my best to solve the problem. I've listed some of the methods I've tried below.
 
**display.setScanPattern({LINE, ZIGZAG,ZZAGG, ZAGGIZ, WZAGZIG, VZAG, ZAGZIG});** I tried all of them.
**display.setMuxPattern({BINARY, STRAIGHT});**  I tried both with all scan pattern options.
**display.setPanelsWidth(2);**  I tried, the result did not change.
**display.setDriverChip(FM6124);** I tried, the result did not change.
**display.setFlip(true);** I tried, the result did not change.
**display.begin(8, 14, 13, 12, 4);**  I tried, the result did not change.

I am using Nodemcu v3. Cable connections are as follows

![229366888-fcb4b749-fb82-40c3-b5d5-b6386fc4f013](https://github.com/2dom/PxMatrix/assets/64726253/06d24a68-3909-4fa7-b18f-e8d40c167c45)

I'm using a 32x16 p6 panel.

![screen1](https://github.com/2dom/PxMatrix/assets/64726253/09642a65-074d-4f5f-a8e3-323fe5fad25e)
![screen2](https://github.com/2dom/PxMatrix/assets/64726253/39ec790c-73f3-46c2-89f6-584576837fa5)

I am waiting for your help to solve the problem. Thank you very much.

**Comment by 2dom** [comment]
Seems that the left an right side are swapped on this panel - the library currently does not support such panels - sorry
