### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by ToXIcGaming** [2dom/PxMatrix#33]

**Comment by ToXIcGaming** [comment]
So I have figured out its possible to do it using adafruit GFX.

**Comment by CTWF** [comment]
I make custom font with Adafruit font creator

**Comment by ToXIcGaming** [comment]
So I can use the fonts but when using a certain font (TomThumb) there is a problem, as you can see ![here](https://i.imgur.com/TlANlCD.jpg)

when using a different font (Picopixel), it works fine ![here](https://i.imgur.com/cH1uGzU.jpg)

I have no idea why this is happening.

**Comment by CTWF** [comment]
Not yet try this font. Because, i made custom font to fit my need.

**Comment by 2dom** [comment]
There is an issue with the display width that is passed to the AdafruitGFX library - if it is set correctly TomThumb will wrap prematurely.

You can fix this by adding

`#define ADAFRUIT_GFX_EXTRA 10`

before

`#include <PxMatrix.h>`
