### ISSUE TITLE
Refresh rate benchmark

### ISSUE THREAD

**Issue by devRomeos** [2dom/PxMatrix#333]
Not sure if this is the place to ask this.
I would like to know if there are some charts or way to calculate how far can push esp32 images to a panel with this library, looking for archive +1500hz 32x32@3bit.

Anyone with fast outdoor panel wanna share results?

Thanks

**Comment by 2dom** [comment]
This library is optimized for low pin-count. If you have an ESP32 (which has sufficient I/Os) and need high refresh rates I suggest using another library that supports DMA.
