### ISSUE TITLE
Power Supply & VCC Connection

### ISSUE THREAD

**Issue by w4ilun** [2dom/PxMatrix#4]
Great Project @2dom !

Is the P10 VCC shared with the NodeMCU? What's the current draw of the panel itself? Would a 2A USB power supply be sufficient?

Thanks!

**Comment by 2dom** [comment]
Hi,

Power consumption really depends on brightness. If you don‘t overdo it, 2A are enough. I simply solder VCC to the either the input diode or the voltage regulator (depending on the model of the NodeMCU) and then use a 2A usb charger to power it.

Best

Dom

**Comment by w4ilun** [comment]
Great, thanks for the reply!
