### ISSUE TITLE
ESP32 and sdcard

### ISSUE THREAD

**Issue by ebelouet** [2dom/PxMatrix#41]
HI,

I search a code eaxmple witj Pxmatrix and reading picture on sd card ?

Sincerely
Eric

**Comment by 2dom** [comment]
It's really just reading a file from the sd card, e.g. see https://www.arduino.cc/en/Tutorial/ReadWrite,
and writing it to memory. Google is your friend here ... many examples on how to display images on LCD/TFT displays from SD card - pxmatrix is not any different here.
