### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ToXIc-Dev** [2dom/PxMatrix#42]
Would be useful if some more examples could be added, similar to the ones on the [Raspberry PI](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use) version.

**Comment by 2dom** [comment]
... no time for more examples atm :( ... wanna create a few ? :)

**Comment by 2dom** [comment]
Haha...come on...I believe in you 😀

**Comment by tablatronix** [comment]
I have ported all adafruit examples, I will try to PR them this week

**Comment by 2dom** [comment]
Did you in the end?

**Comment by tablatronix** [comment]
Sorry my matrix was put away for a bit, I will revisit soon, I can post what I have to gist for now

**Comment by justsilviu** [comment]
Hello.
A simple picture with how the wiring for multiple panels in the readme would help.
i understand how  2 or 3 in a single row work, and i have tried and it works.
but how about creating a matrix of 3x3, how should that be wired?
and "display.setPanelsWidth();" function does not have a corespoding display.setPanelsHeight(); ??
thanks

**Comment by ToXIc-Dev** [comment]
> Hello.
> A simple picture with how the wiring for multiple panels in the readme would help.
> i understand how 2 or 3 in a single row work, and i have tried and it works.
> but how about creating a matrix of 3x3, how should that be wired?
> and "display.setPanelsWidth();" function does not have a corespoding display.setPanelsHeight(); ??
> thanks

This is not really related to this issue, you should create a new issue.

**Comment by ToXIc-Dev** [comment]
> Sorry my matrix was put away for a bit, I will revisit soon, I can post what I have to gist for now

Would be great if you could.

**Comment by 2dom** [comment]
Any news on those examples - did I miss a pull request?

**Comment by tablatronix** [comment]
I just found them yesterday, I never commited it to my fork. I will clean them up and PR it.

**Comment by 2dom** [comment]
Great

**Comment by tablatronix** [comment]
haha geez what a year
I totally kept dropping the ball on this, I actually JUST got around to touch back to this project I was using this for..
