### ISSUE TITLE
DrawCenterText in PxMatrix library or equivalent

### ISSUE THREAD

**Issue by RobertHolscher** [2dom/PxMatrix#44]
Dear All
I love the PxMatrix library but I am looking for a solution to center my numbers on the matrix and keep them centered. The numbers have the top left location as the cursor setting and therefore is the numbers go above 9 (10, 30, and 100) the location shifts. I would like to center align or right top corner as a reference. However I have not seen a function like that in the PX matrix. Any ideas ?

**Comment by 2dom** [comment]
Text is drawn by the AdafruitGFX library not pxmatrix itself. So you may want to submit an issue with them if you like to. In the meantime you could always center it yourself by adding a a varying number of spaces before the number ...
