### ISSUE TITLE
We want support on Led p10 red 

### ISSUE THREAD

**Issue by kushalsharma07** [2dom/PxMatrix#49]
Hi 2dom this is kushal Sharma from hindustanmechanosolutions@gmail.com
Can I get library support for red led p10. We are using uno with the current resource.
https://github.com/freetronics/DMD2
And this one with esp 8266 is not stable. It crashes as we start Web server in nodemcu, and try to read serial or file from spiff memory. 

If possible provide us with new pin configuration for red led p10 panel. That could be run by the same code.

**Comment by CTWF** [comment]
I use dmd2 esp nodemcu, without crash as webserver.

**Comment by kushalsharma07** [comment]
Did you used it as it is. Or you changed something in it. When we tried it,
it crashed every time we think it was lacking ram. Like DMD2 store enough
buffer length in ram for display.

**Comment by CTWF** [comment]
Set it as it is. You can post your code at dmd2 issue.
I think px matrix can support p10 single color.

**Comment by 2dom** [comment]
Not officially...if you have a single panel (no chaining) you might get it to work somehow....

**Comment by kushalsharma07** [comment]
Hey,

I just signed the petition "Ban The Dog And Cat Meat Trade - Coronavirus Is
Only The Beginning" and wanted to see if you could help by adding your name.

Our goal is to reach 200,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/9hww7RQVxr

Thanks!
Kushal

**Comment by PerdanaElang** [comment]
> Saya menggunakan dmd2 esp nodemcu, tanpa crash sebagai webserver.

How to ? I tried repeatedly to find no results
