### ISSUE TITLE
Scanning Issue

### ISSUE THREAD

**Issue by bridge2nowhere** [2dom/PxMatrix#5]
I'm getting a weird effect. I purchased [this panel](https://www.aliexpress.com/item/SRY-1-4-Scan-10mm-Pixel-Pitch-LED-Advertising-Digital-Display-Board-Dot-Matrix-32x16-P10/32711913253.html?spm=a2g0s.9042311.0.0.UjdxP5).

I have it wired correctly, I set it for 1/4 scan, and the pixel test does three lines (and skips one) for each scan. Then it does two middle lines, then top, skip, middle, skip. Then some random purples leds scan across.

I've tried 8,16, and 32 but they don't work either. Am I missing something silly?

Here is a video if that helps:
[https://www.dropbox.com/s/tvim4a4pbq30cc1/IMG_4764.MOV?dl=0](https://www.dropbox.com/s/tvim4a4pbq30cc1/IMG_4764.MOV?dl=0)

**Comment by 2dom** [comment]
That looks very weird indeed ... could you send a high res picture of the back of your matrix including your wiring?

**Comment by bridge2nowhere** [comment]
![Photo as requested](https://user-images.githubusercontent.com/38335227/39754967-fcb5926a-5291-11e8-8878-e29684cfb972.png)

The pinout, not well pictured is

```
R1||G1
B1||Gnd
R2||G2
B2||Gnd
 A||B
 C||D
CK||LAT
OE||GND
```

**Comment by 2dom** [comment]
Sorry...cannot see anything on the pic...

**Comment by bridge2nowhere** [comment]
I'm sorry, are these better?
![img_4772](https://user-images.githubusercontent.com/38335227/39878373-310ebb6c-5446-11e8-840b-8528289d57dd.jpg)
![img_4773](https://user-images.githubusercontent.com/38335227/39878374-31192b92-5446-11e8-814c-2f4f4de3be3b.jpg)
![img_4770](https://user-images.githubusercontent.com/38335227/39878375-312654e8-5446-11e8-963e-6a0030301bb7.jpg)
![img_4769](https://user-images.githubusercontent.com/38335227/39878376-31353fbc-5446-11e8-8905-7fe6a7a6538a.jpg)
![img_4774](https://user-images.githubusercontent.com/38335227/39878378-314b9744-5446-11e8-89e0-069d9a531a4f.jpg)
![img_4775](https://user-images.githubusercontent.com/38335227/39878379-315b1b24-5446-11e8-9e83-1633c5d42867.jpg)
![img_4776](https://user-images.githubusercontent.com/38335227/39878380-316c04f2-5446-11e8-9f89-6b4e56f1bf12.jpg)
![img_4777](https://user-images.githubusercontent.com/38335227/39878382-317a505c-5446-11e8-974a-d56b7e8385ee.jpg)

**Comment by NeoTrace82** [comment]
got the same pannel, just wanted to write an issue,
seems like the Patterns are missorderd

**Comment by Kamal-Sonani** [comment]
[THIS LINK](http://www.instructables.com/id/Tetris-Time-on-a-P10-RGB-Matrix-With-ESP8266/)

I also comment this type of problem 
See pictures and one Video about that.

It is P10 outdoor module which i generally used to make rgb led screen driven by ready-made chinese controller [HD W60 75](http://www.huidu.cn/product/showproduct.php?lang=en&id=41)

**Comment by 2dom** [comment]
@Kamal-Sonani ... could you please also run the pattern test and send me a video of the result (I need to see at least two red,yellow, white sequences)

**Comment by 2dom** [comment]
@bridge2nowhere What is really strange about this is that we just shift in one byte after the other but you display lights up 2bytes worth of LEDs. Could you try pulling all A,B,C pins to ground and repeat the pattern test? (I need to see at least two red,yellow, white sequences)

**Comment by 2dom** [comment]
Great ... I think we might be getting somewhere. It appears that these panels use a different method of row addressing (no multiplexing at all - just pulling on of 4 lines to low). Please pull the new version of the github master (I just updated the library) and put

```
display.begin(4);
display.setMuxPattern(STRAIGHT); 
```

in the setup and let me know if it works (and send a video if it doesn't :)

**Comment by bridge2nowhere** [comment]
No change, it's exactly the same as the last video I posted.

**Comment by 2dom** [comment]
DId you re-attach all the ABCD line to the microcontroller?

**Comment by JammyDodger231** [comment]
This is what my panel is doing with the new code in place and ABCD pins connected: https://photos.app.goo.gl/5CFbC3QFbDbslw9Y2

The code I have used is as follows:
`#include <PxMatrix.h>


#ifdef ESP32

#define P_LAT 22
#define P_A 19
#define P_B 23
#define P_C 18
#define P_D 5
#define P_E 15
#define P_OE 2
hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;

#endif

#ifdef ESP8266

#include <Ticker.h>
Ticker display_ticker;
#define P_LAT 16
#define P_A 5
#define P_B 4
#define P_C 15
#define P_D 12
#define P_E 0
#define P_OE 2

#endif
// Pins for LED MATRIX

PxMATRIX display(32,16,P_LAT, P_OE,P_A,P_B,P_C,P_D);

#ifdef ESP8266
// ISR for display refresh
void display_updater()
{
  display.displayTestPattern(70);
  //display.display(70);
}
#endif

#ifdef ESP32
void IRAM_ATTR display_updater(){
  // Increment the counter and set the time of ISR
  portENTER_CRITICAL_ISR(&timerMux);
  //isplay.display(70);
  display.displayTestPattern(70);
  portEXIT_CRITICAL_ISR(&timerMux);
}
#endif


uint16_t myCYAN = display.color565(0, 255, 255);
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
  display.begin(4);
  display.flushDisplay();
  display.setTextColor(myCYAN);
  display.setMuxPattern(STRAIGHT); 
  display.setCursor(2,0);
  display.print("Pixel");
  Serial.println("hello");

  #ifdef ESP8266
    display_ticker.attach(0.002, display_updater);
  #endif

  #ifdef ESP32
    timer = timerBegin(0, 80, true);
    timerAttachInterrupt(timer, &display_updater, true);
    timerAlarmWrite(timer, 2000, true);
    timerAlarmEnable(timer);
  #endif

  delay(1000);
}


void loop() {

 delay(100);

}`

**Comment by bridge2nowhere** [comment]
I did forget the ABCD lines, I will test again tomorrow to see if get the same result as @JammyDodger231

**Comment by JammyDodger231** [comment]
With the addition of @2dom's new code I get what I see in my video, if I comment out the new line `display.setMuxPattern(STRAIGHT); ` then I get the same initial video as @bridge2nowhere

**Comment by 2dom** [comment]
Ok ... had a typo in the code ... uploaded a new version. Can you try again?

**Comment by 2dom** [comment]
Just keep testing if you don't mind ... I think we almost got it ... try 52b3510

**Comment by JammyDodger231** [comment]
Of course 👍  Pulling now

**Comment by 2dom** [comment]
oh ... and you have to put the display.setMuxPattern(STRAIGHT); before display.begin() for now

**Comment by JammyDodger231** [comment]
Changes pulled and made the alteration to my sketch so the MuxPattern is before the begin, this is the result now:
https://photos.app.goo.gl/nsJxIOM83vofjmZw1

**Comment by 2dom** [comment]
looks perfect ... time to try Pixeltime with 

```
void display_updater()
{
//display.displayTestPattern(70);
display.display(50);
}
```

**Comment by JammyDodger231** [comment]
It's close, I have added an image to show what I see. Here is my new sketch: https://gist.github.com/JammyDodger231/61c20563749e86912efea85cb425e696
![img_20180514_195421](https://user-images.githubusercontent.com/10724551/40017310-e6346a92-57b0-11e8-8e2d-139ea99c52ba.jpg)

**Comment by 2dom** [comment]
ok ... next one ... f00f8a7 is up (this is more a guess what it could be but try anyway :)

**Comment by JammyDodger231** [comment]
Looks closer again! :) 
![img_20180514_201550](https://user-images.githubusercontent.com/10724551/40018312-d22a8380-57b3-11e8-8f96-c0ab7cddda8c.jpg)

**Comment by 2dom** [comment]
could you put a 
```
for (int xx=0, xx<16;xx++);
display.drawPixelRGB888 (xx,xx,128,128,0);
```
in the sketch?

**Comment by 2dom** [comment]
wow ... wtf is that. I rolled back the last change ... lets try again 8c7858f

**Comment by JammyDodger231** [comment]
Almost the same as previous, just shifted over by three it seems:

**Comment by 2dom** [comment]
hey @JammyDodger231 ... I will have to analyze this a bit. Let's continue another day - thanks for you help!

**Comment by JammyDodger231** [comment]
No problem! Thanks for the help so far 😄 Any progress is still progress!

**Comment by 2dom** [comment]
OK ... I created a new test to expose the pattern in detail. Please pull the new libraray and place

```
void display_updater()
{

  display.displayTestPixel(70);

}
```

in your sketch (and post the result).

**Comment by JammyDodger231** [comment]
Changed now, new test gist: https://gist.github.com/JammyDodger231/22bbcc24700a3a2404a3582358a08830 
New video:
https://photos.app.goo.gl/RbL8Qcd5pSFEqfCLA
Two complete cycles

**Comment by 2dom** [comment]
OK ... could you pull the new version and try it with

```
display.begin(4);
display.setMuxPattern(STRAIGHT); 
display.setScanPattern(ZAGGIZ);
```

then run 

```
for (int xx=0, xx<16;xx++);
display.drawPixelRGB888 (xx,xx,128,128,0);
```

in somewhere.

**Comment by 2dom** [comment]
oh ... and don't forget to put

```
void display_updater()
{
//display.displayTestPattern(70);
display.display(50);
}
```

in again

**Comment by JammyDodger231** [comment]
It looks like your most recent stuff isn't pushed, the last update was 2 hours ago :)

**Comment by 2dom** [comment]
my apologies ... should be up now

**Comment by 2dom** [comment]
0bd9e95

**Comment by JammyDodger231** [comment]
Cool I will test now :)

**Comment by 2dom** [comment]
sorry ... fucked some stuff up ... try again cbaf7ef

**Comment by 2dom** [comment]
try again ? d531df3

**Comment by JammyDodger231** [comment]
Awesome! That seems to have done the trick, I don't imagine you need a video or anything but if you do just let me know :) Thank you for taking the time to sort this out 😄 
![img_20180515_213754_hht](https://user-images.githubusercontent.com/10724551/40082253-595393e0-5888-11e8-94c3-de5d3a4495a3.jpg)

**Comment by 2dom** [comment]
Yay ... success. What are weird ass display! Glad that it works! 
Maybe send me a picture of your project if you're finished ... always curious what other makers are up to :)

**Comment by JammyDodger231** [comment]
Definately will do, its a work in progress but will show you what it looks like, most of it will be copied from your tutorial since it looks good :)

**Comment by 2dom** [comment]
A pleasure...have fun :)
