### ISSUE TITLE
swapped blue and green

### ISSUE THREAD

**Issue by dragondaud** [2dom/PxMatrix#50]
I use this library in [myClock](https://github.com/dragondaud/myClock) and ran into an odd issue yesterday. I was hooking up a new matrix panel, one that looked basically the same as previous panels I have used, but the green and blue were swapped. Seems like it may be a hardware variation. I'm using a "matrix shield" pcb that plugs directly into the back of the display, and it works correctly on other displays.

Is there a software method to swap the colors on this aberrant unit? Or other suggestions?

**Comment by 2dom** [comment]
Not for now ... you could work around this by just specifying everything in RGB, e.g. 

`drawPixelRGB888( x, y, r, b ,g);`
