### ISSUE TITLE
strange 64 x 64 Matrix - any ideas?

### ISSUE THREAD

**Issue by kr0815** [2dom/PxMatrix#55]
I have some 3,5mm 64 x 64 Pixel Panels laying around which i want to give a second live - they are from video walls.

They have only one connector

I can´t get any picture / Working LED , panel only stays black
I wonder, as it´s 64 x 64 Pixel, it should be 1/32 Scan, but only 4 latch inputs A0 - A3?
It has also additional to RGB 0 and RGB 1  RGB 2 and RGB 3
I assume OR0 means  Output R0?
(In the Original cabinet, PCBs are not daisy-chained)

SQ,,C,S,D,Q  i´d say are for the onboard EEPROM that stores calibration data, so not needed?

Any idea how to start to get at least some leds blinking / lighting up?
 
Pins are labeled:
R0    OR0
G0    OG0
B0    OB0
R1    OR1
G1    OG1
B1    OB1
CLK  SQ
GND   C
GND   S
GND  D
VCC   Q
VCC  VCC
VCC  VCC
LAT  VCC
OE  GND
A0  GND
A1  GND
A2  OR2
A3  OG2
R2  OB2
G2  OR3
B2  OG3
R3  OB3
G3  B3

**Comment by 2dom** [comment]
No idea ... sorry
