### ISSUE TITLE
pxmatrix and wifi.h seem incompatible on ESP32

### ISSUE THREAD

**Issue by fotosettore** [2dom/PxMatrix#56]
i tried to use a esp32 development board  (you know : more memory and speed  compared to esp8266)  with 64x64 panel.
my goal is to connect to internet and write on panel the info from my solar system server
inside sketch there are pxmatrix library and wifi.h (#include).
compilation is ok but as soon as it runs a fast and continuous flashing of blue on board led is present.
reading the log here is the error (it is written every time led is on) : 

......................
Rebooting...
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40081035  PS      : 0x00060530  A0      : 0x800d1caa  A1      : 0x3ffb1f50  
A2      : 0x00000007  A3      : 0x00000002  A4      : 0x0000000c  A5      : 0x0000000d  
A6      : 0x00000004  A7      : 0x00000000  A8      : 0x3f40217c  A9      : 0x00000000  
A10     : 0xffffffff  A11     : 0x00000064  A12     : 0x08000000  A13     : 0x00000000  
A14     : 0xffffffff  A15     : 0x00000001  SAR     : 0x0000001a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xffffffff  LBEG    : 0x400d3568  LEND    : 0x400d35ca  LCOUNT  : 0x00000002  

Backtrace: 0x40081035:0x3ffb1f50 0x400d1ca7:0x3ffb1f70 0x4011b983:0x3ffb1fa0
...................

Where am I doing wrong ?

**Comment by GeorgeFlorian** [comment]
I have the same issue !

A fix would be great !

**Comment by fotosettore** [comment]
hi dominic
why closed?
no solution ?

**Comment by 2dom** [comment]
Hi,we can leave it open if you like. Won't be able to look into this anytime soon though...Did you get your Fm6126 panels working in the end?BestDomOn 10 May 2019 20:39, fotosettore <notifications@github.com> wrote:hi dominic
why closed?
no solution ?
