### ISSUE TITLE
not printing correctly for 1/8 scan 

### ISSUE THREAD

**Issue by desiboy17** [2dom/PxMatrix#57]

**Comment by desiboy17** [comment]
i am using 32*32 1/8 hub75 led panel with esp32 . I tried all sketchs but ended up with missing pixels.

**Comment by desiboy17** [comment]
![img_20190103_143117](https://user-images.githubusercontent.com/46342120/50629950-b50a2d00-0f64-11e9-9745-295627b9c068.jpg)

**Comment by desiboy17** [comment]
this is what i am getting printed.

**Comment by desiboy17** [comment]
yes, as my matrix panel has three data lines that is A,B and C.
I have selected 1/8 and also tried others i.e 1/16,1/32,1/4.
but the best result is 1/8 in which some pixels are missing.

**Comment by desiboy17** [comment]
Is there any in the library with ESP32 ? Have you tested this with ESP32 ?

**Comment by desiboy17** [comment]
also i have tried different scan pattern i.e. line ,zigzag ,zagziz.

**Comment by 2dom** [comment]
This may be an unsupported pattern ... can you run the pattern_test.ino

**Comment by desiboy17** [comment]
this is not a patter ..i have written "Pixel time"
and yes i have tried 'pattern_test.ino' too.

my board has only three data lines A,B and C and resolution is 32*32.

**Comment by 2dom** [comment]
Yes ...  please run the pattern test sketch from examples and post the result
