### ISSUE TITLE
Release to the Arduino Library Manager

### ISSUE THREAD

**Issue by witnessmenow** [2dom/PxMatrix#6]
Hi @2dom ,

Could we get this library released to the library manager?

You have the library in the correct format, you just need to:

- create a Github release with a version number in the semver format (V1.0.0)
- [Open a issue with the Arduino Github](https://github.com/arduino/Arduino/issues) requesting your library to be added

Thanks!

**Comment by 2dom** [comment]
Hi,

thanks for pointing out how that works ... all done.

Cheers

Dom
