### ISSUE TITLE
_mux_pattern never set default.

### ISSUE THREAD

**Issue by DaveDavenport** [2dom/PxMatrix#63]
Version: Git 3fc6cc05d832f8543e30d34eca8afea1a4689bd3

It looks like _row_pattern is initialized to the default value of _mux_pattern.  (then overwritten in begin).

_mux_pattern is never set. (unless the setter is explicitly called.)

https://github.com/2dom/PxMatrix/blob/3fc6cc05d832f8543e30d34eca8afea1a4689bd3/PxMatrix.h#L208

**Comment by 2dom** [comment]
Not quite sure if I fully understand. _mux_pattern was not initialized. It is now set to STRAIGHT in begin.

What's the issue with _row_pattern?

**Comment by DaveDavenport** [comment]
Row pattern is set to binary:
https://github.com/2dom/PxMatrix/blob/3fc6cc05d832f8543e30d34eca8afea1a4689bd3/PxMatrix.h#L284

But it is the interval right? (and BINARY is enum entry for _mux_pattern).

**Comment by 2dom** [comment]
Yep ... killed the init ... thanks!
