### ISSUE TITLE
Help correct code

### ISSUE THREAD

**Issue by ffnull** [2dom/PxMatrix#70]
Im got p10 32x16. im connect all like in manual. My matrix had only A and B. But it doesnt correct work
https://youtu.be/0daGIZM5h6s

**Comment by 2dom** [comment]
Can you post your code?

**Comment by ffnull** [comment]
Im use standart example

чт, 21 февр. 2019 г., 08:57 Dominic Buchstaller <notifications@github.com>:

**Comment by ffnull** [comment]
So, any help?

**Comment by 2dom** [comment]
Whats the problem with it? Your pattern test seems fine.

It appears to be a 1/4 scan panel so you will have to use `display.begin(4);`

**Comment by ffnull** [comment]
Yes. Im try but thre space between images. So its different scan

пт, 22 февр. 2019 г., 11:52 Dominic Buchstaller <notifications@github.com>:

**Comment by 2dom** [comment]
Can you post a picture of the problem?

**Comment by ffnull** [comment]
Please wait 5 minutes. I need to assembly all

пт, 22 февр. 2019 г., 12:02 Dominic Buchstaller <notifications@github.com>:

**Comment by ffnull** [comment]
https://youtu.be/mkLAldZu10Y see how text Adafruit Matrix shows. There 2
rows that wrong

пт, 22 февр. 2019 г., 12:05 FFNULL DEV <djmorganfreeman@gmail.com>:

**Comment by 2dom** [comment]
Did you try setting the scan pattern with

```
display.begin(4);
display.setScanPattern(x);
```
where x can be LINE, ZIGZAG, ZAGGIZ, WZAGZIG, VZAG. (see github readme)

**Comment by ffnull** [comment]
Yes. Best results was with zigzag. But missed 4 lines

пт, 22 февр. 2019 г., 13:24 Dominic Buchstaller <notifications@github.com>:

**Comment by ffnull** [comment]
Any solution?

**Comment by ffnull** [comment]
Please close issue. All is fine. Problem was with broken wire on p10 board. Factory fault.

**Comment by 2dom** [comment]
Ok.. nevermind
