### ISSUE TITLE
Support of Adafruit GFX drawChar()

### ISSUE THREAD

**Issue by RobertHolscher** [2dom/PxMatrix#77]

**Comment by RobertHolscher** [comment]
I would like to get support of the Adafruit GFX function drawChar() in the PX matrix. My compiler says it is not an available function. Is this right or am I overlooking something?

**Comment by 2dom** [comment]
PxMatrix simply inherits the AdafruitGFX class... whatever is implemented there is supported by PxMatrix....

**Comment by RobertHolscher** [comment]
But drawChar is member of the Adafruit GFX but not recognized by the PX matrix class

**Comment by 2dom** [comment]
Did you maybe use an old version of AdafruitGFX in your library folder?On 11 Mar 2019 21:54, RobertHolscher <notifications@github.com> wrote:But drawChar is member of the Adafruit GFX but not recognized by the PX matrix class

**Comment by RobertHolscher** [comment]
Sorry for my late reaction, but I have to check if the latest library is in my folder. I will check this later and will let you know
