### ISSUE TITLE
Problem solved with ESP8266

### ISSUE THREAD

**Issue by 1397v** [2dom/PxMatrix#78]
Hi, just a suggestion for the README.md file.

I was trying for days this library and it didn't work until I realized that my ESP8266 has some pins changed. 

So my module is the Wemos D1 (**NOT THE MINI**), so I said ok I'll use the NodeMCU pins (The ones starting with a 'D'), because those were the ones written in the front of the Wemos D1, to connect the panel. It didn't work. 

After days triying to change the code, I realized of this picture https://cdn.instructables.com/FRI/BY6A/JH0TS7Q1/FRIBY6AJH0TS7Q1.LARGE.jpg
 in the page (https://www.instructables.com/id/RGB-LED-Matrix-With-an-ESP8266/). This picture explains the different mappings of different pin nomenclatures, so I discovered that the Wemos D1 has the GPIO nomenclature of the pins in the back and I gave it a try mapping the NodeMCU nomenclature to that one, and it worked!

So my suggestion for the README file is that you include this nomenclature mapping or the image, so that might help others with problems connecting the led panel.

Sorry for the bad english.

Oh! And an **IMPORTANT Fact** is that the pattern_test.ino was working correctly before I changed the connections, but the other examples weren't. I realized of this when trying to simply print "hello".

**Comment by 2dom** [comment]
Thanks for the info - this will serve others with the Wemos D1 as a reference. I won't add this to the Readme though as there are so many chips and variants it would make it rather bloated.
