### ISSUE TITLE
Not an Issue, Just need information for understanding

### ISSUE THREAD

**Issue by khawajamechatronics** [2dom/PxMatrix#81]
Hi,

I am trying to interface P10 Led Panel with Arduino.

At first I tried it with Arduino Mega and used wiring as indicated in adafruit tutorial
https://learn.adafruit.com/32x16-32x32-rgb-led-matrix?view=all

In that they have used R1 G1 B1 R2 G2 B2 connected to MCU as well.

In your library only R1 is connected to MCU and other to end connector.

Can you explain the logic?

Although I have tried one time to get it work with your library but have some issue. I will try one more time today again.

I shall be thankful for you if you help me understand and also get it working.

Regards.

**Comment by 2dom** [comment]
Please read the github Readme .... it's all there
