### ISSUE TITLE
Are there any tutorials ? How do you actually use this library ?!

### ISSUE THREAD

**Issue by GeorgeFlorian** [2dom/PxMatrix#85]
Hello !
After some tinkering I think I got this library to work.

Display: [2727 SMD P5 64x32](https://www.aliexpress.com/item/SMD-2727-P5-outdoor-Video-wall-led-module-high-brightness-5500-nits-1-8-scan-64/32788680216.html)
Board: ESP32 Wrover-B DevKitV4

This is the setup:
![](https://i.postimg.cc/W1WH3FFT/20190409-154238.jpg)

![](https://i.postimg.cc/HxFD6TqD/Px-Matrix-Schematics.png)

I want to know how do I use it. Where can I find a tutorial or something. What are the function and what do they do ?

I would like to know how to set the refresh rate and the brightness.
The only thing that do something is:
`uint8_t display_draw_time=20;` 
But no matter the number, the refresh rate hurts my eyes. It's brutal.

Also I need to use `display.setTextColor(display.color565(colorR/8,colorG/8,colorB/8));` in the PixelTime example, because if I don't put /8 after each color, ghosting happens.
What does that actually do ? Why isn't there no documentation ? I am sorry, but I don't understand how to use this library, and I would very much like to. Thank you !

I've modified the PixelTime example as follows: 

```
#include <PxMatrix.h>

#define P_LAT 22
#define P_A 19
#define P_B 23
#define P_C 18
#define P_D 4
#define P_E 15
#define P_OE 25

#define matrix_width 64
#define matrix_height 32

hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;

// This defines the 'on' time of the display is us. The larger this number,
// the brighter the display. If too large the ESP will crash

uint8_t display_draw_time=20; //10-50 is usually fine

PxMATRIX display(matrix_width,matrix_height,P_LAT, P_OE,P_A,P_B,P_C,P_D,P_E);


void setup() {
 Serial.begin(9600);
  // Define your display layout here, e.g. 1/8 step
  display.begin(8);

//  display.setFastUpdate(false);
  display.clearDisplay();
  display.setTextColor(myCYAN);
  display.setCursor(2,0);
  display.print("Pixel");
  display.setTextColor(myMAGENTA);
  display.setCursor(2,8);
  display.print("Time");

  delay(3000);

}

void loop() {
}
```

And nothing happens... How can I fill up the Display with just 2 words on 2 rows ?

Better yet, I would like the Display to behave like a vector with 4 values.
In the end I would like to display only 4 BIG numbers on it.

Thank you !

**Comment by GilDev** [comment]
No, documentation is quite light right now, you should look at the source and tinker to make it work like you want to. Also look at the closed issues, it may help.

**Comment by GeorgeFlorian** [comment]
> No, documentation is quite light right now, you should look at the source and tinker to make it work like you want to. Also look at the closed issues, it may help.

I made it work. I replaced it though because it doesn't work with ESPAsyncWebServer.

**Comment by GilDev** [comment]
Alright great. What did you use to replace it?
