### ISSUE TITLE
Strange behaviour of the LED display, image strongly distorted

### ISSUE THREAD

**Issue by TyskieGronie** [2dom/PxMatrix#93]
Hello,

I have been trying for several days to get a LED display from Lysonled (P3 1/16 scan, 64x32 pixels) with FM6126A chipset to work.

I get a picture displayed but the result is strongly falsified.
I already tried a different controller (D1 Wemos Mini & NodeMCU), power supply and cables. Unfortunately without success.

I checked the wiring several times and can't find any error.

**Mario:**
[Click](http://sendvid.com/770migz5)
_Mama Mia ..._

**With controller switched off:**
[Click](http://sendvid.com/are4e79v)

**Pixel Time:**
[Click](http://sendvid.com/jyg73ury)

**Connecting GND from HUB75 (PIN bottom right):**
[Click](http://sendvid.com/dfs2kvck)

I would be very happy about your support and advice on what else it could be.

**Comment by TyskieGronie** [comment]
I've been experimenting. My cabling is basically the same as shown here but with a NodeMCU.

![F13DT7VJH0TS7PZ LARGE](https://user-images.githubusercontent.com/49958041/56848642-aff23480-68eb-11e9-9581-a605647fc7d0.jpg)

I connected the NodeMCU to the 5V power supply of the LED matrix.
As soon as I connect the GND pin as shown in the sketch (black wire), the signal breaks off.

If I power the NodeMCU via USB the result is as shown in the video.
As soon as I ground the LED panel against the NodeMCU, the signal breaks off or is distorted as seen in the last video.

**Comment by 2dom** [comment]
Hard to say whats wrong here - this funny effect is usually due to improper initialization of the chip. Try turning everything off, then power the LED panel, then the MCU.

**Comment by TyskieGronie** [comment]
First of all I want to thank you for your great work and spare time you put into this library.

Unfortunately, I couldn't solve the problems and eventually switched to my Raspberry and another library.

For the Raspberry there is the Adafruit RGB Matrix Bonnet, with which it worked almost immediately. Probably this was the better choice for me, a amateur in electrical engineering.

It took me many frustrating hours to locate and solve the problems with the FM6126A chip. I finally failed with the wiring.

The result is still impressive with the Raspberry and Adafruit Bonnet:

![Unbenannt](https://user-images.githubusercontent.com/49958041/57720964-47dd7580-7683-11e9-89e6-7a3cd5553753.jpg)

**Comment by 2dom** [comment]
No worries man...I'm glad you got it working and a bit mad that it was not with PxMatrix. 

The FM6126A chip is just terrible and unfortunately I don't have the time to create proper support. 

Cheers !
