### ISSUE TITLE
Strange Pattern

### ISSUE THREAD

**Issue by pyzimmer** [2dom/PxMatrix#94]
Hello,
I bought this panel : https://fr.aliexpress.com/item/P4-Outdoor-256-128mm-64-32-pixels-1-8scan-3in1-RGB-SMD-P4-Full-Color-LED/32836331716.html?spm=a2g0w.10010108.1000016.1.1385ec22iQp5yC&isOrigTitle=true

When I print the caracter "1" , see the result : 
![image](https://user-images.githubusercontent.com/43472705/57374004-20c20800-719a-11e9-818b-913b49f9fc81.png)

The video of the Test scan pattern : https://photos.app.goo.gl/Gfmg2fesxYfiUtDeA

- I use 1/8 scan,
- I use pins ABC (I test D, but seem not connected),
- I test all patterns
- I call : PxMATRIX display(64,32,P_LAT, P_OE,P_A,P_B,P_C);
 
Any idea ? Thank you

**Comment by 2dom** [comment]
try setting the scan pattern:

display.scan_patterns(x) where x is one of  {LINE, ZIGZAG, ZAGGIZ, WZAGZIG, VZAG}

**Comment by pyzimmer** [comment]
Thank you,
I already tested all scan pattern, it's different but not good.
I also tested display.setMuxPattern(STRAIGHT), but no difference with BINARY.

**Comment by 2dom** [comment]
Hm ... this is a pretty weird pattern (ZIZAG with row change after 2 bytes instead of one)  ... I probably haven't supported that one yet. Unfortunately I don't have a lot of time atm - sorry.

**Comment by pyzimmer** [comment]
the best result with VZAG , but there is group of lines switched :
![image](https://user-images.githubusercontent.com/43472705/57479175-20f6fc00-729d-11e9-9135-aee556852d8c.png)

**Comment by pyzimmer** [comment]
I found a trick by adding the line :   
display.setPanelsWidth(4);
It is like there is 4 vertical panels of 16x32 ...

![image](https://user-images.githubusercontent.com/43472705/57525592-71b53600-732b-11e9-814a-05c469a104a3.png)

**Comment by pyzimmer** [comment]
With 2 panels it is OK, but with 3 panels, the display become very slow :
https://photos.app.goo.gl/ZZpw3VDmKG9Ltps19
and the color become orange :
![image](https://user-images.githubusercontent.com/43472705/57530169-f22d6400-7336-11e9-8029-ba3c5d1d12ab.png)

why ?

**Comment by pyzimmer** [comment]
Hello, everything OK !
I solved the slow display by modifying SPI.setFrequency(13000000) in PxMatrix.h
and the orange color by using bigger power supply wire 
thank you

**Comment by tammaaziz** [comment]
Hello!
I have a P10 rgb full color 32x16 display : I tried all available options (display(A, B, {C}, {D}), setScanPattern, setMuxPattern) on the subject using the PxMatrix library with a NodeMCU (ESP12). 

beside, I tried the display.setPanelsWidth(4) as suggested by pyzimmer but does not work .. I am really stuck !! Can anyone help please !

**Comment by adrianrv** [comment]
Awesome! `SPI.setFrequency(13000000)` solved my issue as well. I am using 2 64x64 panels and now works great with no strange pixel colors.
