### ISSUE TITLE
FM6126A SetBrightness

### ISSUE THREAD

**Issue by bastienvans** [2dom/PxMatrix#99]
As you probably noticed, the setBrightness function doesn’t work for the FM6126A chips.

I’ve been trying to mess with the source code for a week now but I am not able to get anything working as my knowledge in the field is limited.

Anyone with some spare time willing to take a look into it?

Thank you!

**Comment by 2dom** [comment]
I won't spend more time on FM6126A related issues as the manufacturers have stopped using them (FM6126A suck big time).

**Comment by zakrava** [comment]
I just bought new p3 panel, and to my surprise, it has FM6126A chip. It looks like, that this is is still widely used. Please can you consider add brightness support for this chip? I am using esp8266.

**Comment by 2dom** [comment]
Brightness support only for esp8266 for now sorry. Don't have the time to port the ESP32 code to esp8266. Do you want to give it a shot ?

**Comment by IAmOrion** [comment]
I'm hoping someone will eventually pick this up (I'm not skilled enough myself), however these damn FM6126A chips, whilst they're apparently not in production any more, the UK at least is FLOODED with these matrix panels! I've bought about 5 this year, all from different companies, different times, differing prices etc.... 4 out of 5 are FM6126A :(
